export const CREATE_CATEGORY_ITEM_REQUEST = '$CATEGORY_ITEM/CREATE_CATEGORY_ITEM_REQUEST'
export const CREATE_CATEGORY_ITEM_SUCCESS = '$CATEGORY_ITEM/CREATE_CATEGORY_ITEM_SUCCESS'
export const CREATE_CATEGORY_ITEM_FAILURE = '$CATEGORY_ITEM/CREATE_CATEGORY_ITEM_FAILURE'

export const EDIT_CATEGORY_ITEM_REQUEST = '$CATEGORY_ITEM/EDIT_CATEGORY_ITEM_REQUEST'
export const EDIT_CATEGORY_ITEM_SUCCESS = '$CATEGORY_ITEM/EDIT_CATEGORY_ITEM_SUCCESS'
export const EDIT_CATEGORY_ITEM_FAILURE = '$CATEGORY_ITEM/EDIT_CATEGORY_ITEM_FAILURE'

export const CREATE_OR_EDIT_CATEGORY_ITEM_CLEAR = '$CATEGORY_ITEM/CREATE_OR_EDIT_CATEGORY_ITEM_CLEAR'

export const DELETE_CATEGORY_ITEM_REQUEST = '$CATEGORY_ITEM/DELETE_CATEGORY_ITEM_REQUEST'
export const DELETE_CATEGORY_ITEM_SUCCESS = '$CATEGORY_ITEM/DELETE_CATEGORY_ITEM_SUCCESS'
export const DELETE_CATEGORY_ITEM_FAILURE = '$CATEGORY_ITEM/DELETE_CATEGORY_ITEM_FAILURE'
export const DELETE_CATEGORY_ITEM_CLEAR = '$CATEGORY_ITEM/DELETE_CATEGORY_ITEM_CLEAR'

export const GET_CATEGORY_ITEM_LIST_REQUEST = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_LIST_REQUEST'
export const GET_CATEGORY_ITEM_LIST_SUCCESS = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_LIST_SUCCESS'
export const GET_CATEGORY_ITEM_LIST_FAILURE = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_LIST_FAILURE'

export const GET_CATEGORY_ITEM_DETAIL_REQUEST = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_DETAIL_REQUEST'
export const GET_CATEGORY_ITEM_DETAIL_SUCCESS = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_DETAIL_SUCCESS'
export const GET_CATEGORY_ITEM_DETAIL_FAILURE = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_DETAIL_FAILURE'

export const GET_CATEGORY_ITEM_ALL_REQUEST = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_ALL_REQUEST'
export const GET_CATEGORY_ITEM_ALL_SUCCESS = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_ALL_SUCCESS'
export const GET_CATEGORY_ITEM_ALL_FAILURE = '$CATEGORY_ITEM/GET_CATEGORY_ITEM_ALL_FAILURE'
