export const GET_PENDING_APPROVALS_REQUEST = 'GET_PENDING_APPROVALS_REQUEST'
export const GET_PENDING_APPROVALS_SUCCESS = 'GET_PENDING_APPROVALS_SUCCESS'
export const GET_PENDING_APPROVALS_FAILURE = 'GET_PENDING_APPROVALS_FAILURE'

export const APPROVE_RKT_REQUEST = 'APPROVE_RKT_REQUEST'
export const APPROVE_RKT_SUCCESS = 'APPROVE_RKT_SUCCESS'
export const APPROVE_RKT_FAILURE = 'APPROVE_RKT_FAILURE'

export const REJECT_RKT_REQUEST = 'REJECT_RKT_REQUEST'
export const REJECT_RKT_SUCCESS = 'REJECT_RKT_SUCCESS'
export const REJECT_RKT_FAILURE = 'REJECT_RKT_FAILURE'

export const GET_RKT_DETAIL_REQUEST = 'GET_RKT_DETAIL_REQUEST'
export const GET_RKT_DETAIL_SUCCESS = 'GET_RKT_DETAIL_SUCCESS'
export const GET_RKT_DETAIL_FAILURE = 'GET_RKT_DETAIL_FAILURE'

export const CLEAR_APPROVAL_STATUS = 'CLEAR_APPROVAL_STATUS'