export const CREATE_CENSUS_REQUEST = '$EPLANT_CENSUS/CREATE_CENSUS_REQUEST'
export const CREATE_CENSUS_SUCCESS = '$EPLANT_CENSUS/CREATE_CENSUS_SUCCESS'
export const CREATE_CENSUS_FAILURE = '$EPLANT_CENSUS/CREATE_CENSUS_FAILURE'

export const EDIT_CENSUS_REQUEST = '$EPLANT_CENSUS/EDIT_CENSUS_REQUEST'
export const EDIT_CENSUS_SUCCESS = '$EPLANT_CENSUS/EDIT_CENSUS_SUCCESS'
export const EDIT_CENSUS_FAILURE = '$EPLANT_CENSUS/EDIT_CENSUS_FAILURE'

export const DELETE_CENSUS_REQUEST = '$EPLANT_CENSUS/DELETE_CENSUS_REQUEST'
export const DELETE_CENSUS_SUCCESS = '$EPLANT_CENSUS/DELETE_CENSUS_SUCCESS'
export const DELETE_CENSUS_FAILURE = '$EPLANT_CENSUS/DELETE_CENSUS_FAILURE'

export const GET_CENSUS_LIST_REQUEST = '$EPLANT_CENSUS/GET_CENSUS_LIST_REQUEST'
export const GET_CENSUS_LIST_SUCCESS = '$EPLANT_CENSUS/GET_CENSUS_LIST_SUCCESS'
export const GET_CENSUS_LIST_FAILURE = '$EPLANT_CENSUS/GET_CENSUS_LIST_FAILURE'

export const GET_CENSUS_DETAIL_REQUEST = '$EPLANT_CENSUS/GET_CENSUS_DETAIL_REQUEST'
export const GET_CENSUS_DETAIL_SUCCESS = '$EPLANT_CENSUS/GET_CENSUS_DETAIL_SUCCESS'
export const GET_CENSUS_DETAIL_FAILURE = '$EPLANT_CENSUS/GET_CENSUS_DETAIL_FAILURE'

export const CREATE_OR_EDIT_CENSUS_CLEAR = '$EPLANT_CENSUS/CLEAR_FORM'
export const DELETE_CENSUS_CLEAR = '$EPLANT_CENSUS/CLEAR_DELETE_STATE'
