export const CREATE_PMA_REQUEST = '$PMA/CREATE_PMA_REQUEST'
export const CREATE_PMA_SUCCESS = '$PMA/CREATE_PMA_SUCCESS'
export const CREATE_PMA_FAILURE = '$PMA/CREATE_PMA_FAILURE'

export const EDIT_PMA_REQUEST = '$PMA/EDIT_PMA_REQUEST'
export const EDIT_PMA_SUCCESS = '$PMA/EDIT_PMA_SUCCESS'
export const EDIT_PMA_FAILURE = '$PMA/EDIT_PMA_FAILURE'

export const EDIT_PMA_EMPLOYEE_REQUEST = '$PMA/EDIT_PMA_EMPLOYEE_REQUEST'
export const EDIT_PMA_EMPLOYEE_SUCCESS = '$PMA/EDIT_PMA_EMPLOYEE_SUCCESS'
export const EDIT_PMA_EMPLOYEE_FAILURE = '$PMA/EDIT_PMA_EMPLOYEE_FAILURE'

export const DETAIL_PMA_REQUEST = '$PMA/DETAIL_PMA_REQUEST'
export const DETAIL_PMA_SUCCESS = '$PMA/DETAIL_PMA_SUCCESS'
export const DETAIL_PMA_FAILURE = '$PMA/DETAIL_PMA_FAILURE'

export const MOBILE_PMA_REQUEST = '$PMA/MOBILE_PMA_REQUEST'
export const MOBILE_PMA_SUCCESS = '$PMA/MOBILE_PMA_SUCCESS'
export const MOBILE_PMA_FAILURE = '$PMA/MOBILE_PMA_FAILURE'

export const SYNC_PMA_REQUEST = '$PMA/SYNC_PMA_REQUEST'
export const SYNC_PMA_SUCCESS = '$PMA/SYNC_PMA_SUCCESS'
export const SYNC_PMA_FAILURE = '$PMA/SYNC_PMA_FAILURE'

export const CREATE_OR_EDIT_PMA_CLEAR = '$PMA/CREATE_OR_EDIT_PMA_CLEAR'

export const CREATE_OR_EDIT_PMA_EMPLOYEE_CLEAR = '$PMA/CREATE_OR_EDIT_PMA_EMPLOYEE_CLEAR'

export const DELETE_PMA_REQUEST = '$PMA/DELETE_PMA_REQUEST'
export const DELETE_PMA_SUCCESS = '$PMA/DELETE_PMA_SUCCESS'
export const DELETE_PMA_FAILURE = '$PMA/DELETE_PMA_FAILURE'
export const DELETE_PMA_CLEAR = '$PMA/DELETE_PMA_CLEAR'

export const GET_PMA_LIST_REQUEST = '$PMA/GET_PMA_LIST_REQUEST'
export const GET_PMA_LIST_SUCCESS = '$PMA/GET_PMA_LIST_SUCCESS'
export const GET_PMA_LIST_FAILURE = '$PMA/GET_PMA_LIST_FAILURE'

export const GET_ALL_PMA_REQUEST = '$PMA/GET_ALL_PMA_REQUEST'
export const GET_ALL_PMA_SUCCESS = '$PMA/GET_ALL_PMA_SUCCESS'
export const GET_ALL_PMA_FAILURE = '$PMA/GET_ALL_PMA_FAILURE'

export const ADD_PMA_TEMP = '$PMA/ADD_PMA_TEMP'
export const EDIT_PMA_TEMP = '$PMA/EDIT_PMA_TEMP'
export const DELETE_PMA_TEMP = '$PMA/DELETE_PMA_TEMP'
export const DELETE_PMA_EMPLOYEE_TEMP = '$PMA/DELETE_PMA_EMPLOYEE_TEMP'

export const CLEAR_DRAFT_PMA_REQUEST = '$PMA/CLEAR_DRAFT_PMA_REQUEST'
export const CLEAR_DRAFT_PMA_SUCCESS = '$PMA/CLEAR_DRAFT_PMA_SUCCESS'
export const CLEAR_DRAFT_PMA_FAILURE = '$PMA/CLEAR_DRAFT_PMA_FAILURE'
