export const CREATE_RKH_TAKE_CARE_REQUEST = '$RKH/CREATE_RKH_TAKE_CARE_REQUEST'
export const CREATE_RKH_TAKE_CARE_SUCCESS = '$RKH/CREATE_RKH_TAKE_CARE_SUCCESS'
export const CREATE_RKH_TAKE_CARE_FAILURE = '$RKH/CREATE_RKH_TAKE_CARE_FAILURE'

export const EDIT_RKH_TAKE_CARE_REQUEST = '$RKH/EDIT_RKH_TAKE_CARE_REQUEST'
export const EDIT_RKH_TAKE_CARE_SUCCESS = '$RKH/EDIT_RKH_TAKE_CARE_SUCCESS'
export const EDIT_RKH_TAKE_CARE_FAILURE = '$RKH/EDIT_RKH_TAKE_CARE_FAILURE'

export const DETAIL_RKH_TAKE_CARE_REQUEST = '$RKH/DETAIL_RKH_TAKE_CARE_REQUEST'
export const DETAIL_RKH_TAKE_CARE_SUCCESS = '$RKH/DETAIL_RKH_TAKE_CARE_SUCCESS'
export const DETAIL_RKH_TAKE_CARE_FAILURE = '$RKH/DETAIL_RKH_TAKE_CARE_FAILURE'

export const SYNC_RKH_TAKE_CARE_REQUEST = '$RKH/SYNC_RKH_TAKE_CARE_REQUEST'
export const SYNC_RKH_TAKE_CARE_SUCCESS = '$RKH/SYNC_RKH_TAKE_CARE_SUCCESS'
export const SYNC_RKH_TAKE_CARE_FAILURE = '$RKH/SYNC_RKH_TAKE_CARE_FAILURE'

export const CREATE_OR_EDIT_RKH_TAKE_CARE_CLEAR = '$RKH/CREATE_OR_EDIT_RKH_TAKE_CARE_CLEAR'

export const DELETE_RKH_TAKE_CARE_REQUEST = '$RKH/DELETE_RKH_TAKE_CARE_REQUEST'
export const DELETE_RKH_TAKE_CARE_SUCCESS = '$RKH/DELETE_RKH_TAKE_CARE_SUCCESS'
export const DELETE_RKH_TAKE_CARE_FAILURE = '$RKH/DELETE_RKH_TAKE_CARE_FAILURE'
export const DELETE_RKH_TAKE_CARE_CLEAR = '$RKH/DELETE_RKH_TAKE_CARE_CLEAR'

export const GET_RKH_TAKE_CARE_LIST_REQUEST = '$RKH/GET_RKH_TAKE_CARE_LIST_REQUEST'
export const GET_RKH_TAKE_CARE_LIST_SUCCESS = '$RKH/GET_RKH_TAKE_CARE_LIST_SUCCESS'
export const GET_RKH_TAKE_CARE_LIST_FAILURE = '$RKH/GET_RKH_TAKE_CARE_LIST_FAILURE'

export const GET_RKH_TAKE_CARE_ALL_REQUEST = '$RKH/GET_RKH_TAKE_CARE_ALL_REQUEST'
export const GET_RKH_TAKE_CARE_ALL_SUCCESS = '$RKH/GET_RKH_TAKE_CARE_ALL_SUCCESS'
export const GET_RKH_TAKE_CARE_ALL_FAILURE = '$RKH/GET_RKH_TAKE_CARE_ALL_FAILURE'

export const GET_ALL_RKH_TAKE_CARE_REQUEST = '$RKH/GET_ALL_RKH_TAKE_CARE_REQUEST'
export const GET_ALL_RKH_TAKE_CARE_SUCCESS = '$RKH/GET_ALL_RKH_TAKE_CARE_SUCCESS'
export const GET_ALL_RKH_TAKE_CARE_FAILURE = '$RKH/GET_ALL_RKH_TAKE_CARE_FAILURE'

export const ADD_RKH_TAKE_CARE_TEMP = '$RKH/ADD_RKH_TAKE_CARE_TEMP'
export const EDIT_RKH_TAKE_CARE_TEMP = '$RKH/EDIT_RKH_TAKE_CARE_TEMP'
export const DELETE_RKH_TAKE_CARE_TEMP = '$RKH/DELETE_RKH_TAKE_CARE_TEMP'

export const CLEAR_DRAFT_RKH_TAKE_CARE_REQUEST = '$RKH/CLEAR_DRAFT_RKH_TAKE_CARE_REQUEST'
export const CLEAR_DRAFT_RKH_TAKE_CARE_SUCCESS = '$RKH/CLEAR_DRAFT_RKH_TAKE_CARE_SUCCESS'
export const CLEAR_DRAFT_RKH_TAKE_CARE_FAILURE = '$RKH/CLEAR_DRAFT_RKH_TAKE_CARE_FAILURE'
