export const CREATE_DAILY_ACTIVITY_REQUEST = '$EPLANT_DAILY_ACTIVITY/CREATE_DAILY_ACTIVITY_REQUEST'
export const CREATE_DAILY_ACTIVITY_SUCCESS = '$EPLANT_DAILY_ACTIVITY/CREATE_DAILY_ACTIVITY_SUCCESS'
export const CREATE_DAILY_ACTIVITY_FAILURE = '$EPLANT_DAILY_ACTIVITY/CREATE_DAILY_ACTIVITY_FAILURE'
export const CREATE_OR_EDIT_DAILY_ACTIVITY_CLEAR = '$EPLANT_DAILY_ACTIVITY/CLEAR_FORM'

export const GET_DAILY_ACTIVITY_LIST_REQUEST = '$EPLANT_DAILY_ACTIVITY/GET_DAILY_ACTIVITY_LIST_REQUEST'
export const GET_DAILY_ACTIVITY_LIST_SUCCESS = '$EPLANT_DAILY_ACTIVITY/GET_DAILY_ACTIVITY_LIST_SUCCESS'
export const GET_DAILY_ACTIVITY_LIST_FAILURE = '$EPLANT_DAILY_ACTIVITY/GET_DAILY_ACTIVITY_LIST_FAILURE'

export const EDIT_DAILY_ACTIVITY_REQUEST = '$EPLANT_DAILY_ACTIVITY/EDIT_DAILY_ACTIVITY_REQUEST'
export const EDIT_DAILY_ACTIVITY_SUCCESS = '$EPLANT_DAILY_ACTIVITY/EDIT_DAILY_ACTIVITY_SUCCESS'
export const EDIT_DAILY_ACTIVITY_FAILURE = '$EPLANT_DAILY_ACTIVITY/EDIT_DAILY_ACTIVITY_FAILURE'

export const DELETE_DAILY_ACTIVITY_REQUEST = '$EPLANT_DAILY_ACTIVITY/DELETE_DAILY_ACTIVITY_REQUEST'
export const DELETE_DAILY_ACTIVITY_SUCCESS = '$EPLANT_DAILY_ACTIVITY/DELETE_DAILY_ACTIVITY_SUCCESS'
export const DELETE_DAILY_ACTIVITY_FAILURE = '$EPLANT_DAILY_ACTIVITY/DELETE_DAILY_ACTIVITY_FAILURE'
export const DELETE_DAILY_ACTIVITY_CLEAR = '$EPLANT_DAILY_ACTIVITY/CLEAR_DELETE_STATE'
