

export const ERROR_NETWORK_REQUEST = "ERROR_NETWORK_REQUEST"
export const ERROR_UNAUTHORIZED_EXPIRED_TOKEN_REQUEST = "ERROR_UNAUTHORIZED_EXPIRED_TOKEN_REQUEST"
export const ERROR_UNAUTHORIZED_REQUEST = "ERROR_UNAUTHORIZED_REQUEST"
export const ERROR_UNDEFINED_STATUS = "ERROR_UNDEFINED_STATUS_INTERNET_OR_SERVER_PROBLEM"

export const LOG_REFRESH_TOKEN = "LOG_REFRESH_TOKEN"


export const getErrorTagNetworkRequest = (tag: string) => `${ERROR_NETWORK_REQUEST}_${tag}`
