export const CREATE_MASTER_ITEM_REQUEST = '$MASTER_ITEM/CREATE_MASTER_ITEM_REQUEST'
export const CREATE_MASTER_ITEM_SUCCESS = '$MASTER_ITEM/CREATE_MASTER_ITEM_SUCCESS'
export const CREATE_MASTER_ITEM_FAILURE = '$MASTER_ITEM/CREATE_MASTER_ITEM_FAILURE'

export const EDIT_MASTER_ITEM_REQUEST = '$MASTER_ITEM/EDIT_MASTER_ITEM_REQUEST'
export const EDIT_MASTER_ITEM_SUCCESS = '$MASTER_ITEM/EDIT_MASTER_ITEM_SUCCESS'
export const EDIT_MASTER_ITEM_FAILURE = '$MASTER_ITEM/EDIT_MASTER_ITEM_FAILURE'

export const CREATE_OR_EDIT_MASTER_ITEM_CLEAR = '$MASTER_ITEM/CREATE_OR_EDIT_MASTER_ITEM_CLEAR'

export const DELETE_MASTER_ITEM_REQUEST = '$MASTER_ITEM/DELETE_MASTER_ITEM_REQUEST'
export const DELETE_MASTER_ITEM_SUCCESS = '$MASTER_ITEM/DELETE_MASTER_ITEM_SUCCESS'
export const DELETE_MASTER_ITEM_FAILURE = '$MASTER_ITEM/DELETE_MASTER_ITEM_FAILURE'
export const DELETE_MASTER_ITEM_CLEAR = '$MASTER_ITEM/DELETE_MASTER_ITEM_CLEAR'

export const GET_MASTER_ITEM_LIST_REQUEST = '$MASTER_ITEM/GET_MASTER_ITEM_LIST_REQUEST'
export const GET_MASTER_ITEM_LIST_SUCCESS = '$MASTER_ITEM/GET_MASTER_ITEM_LIST_SUCCESS'
export const GET_MASTER_ITEM_LIST_FAILURE = '$MASTER_ITEM/GET_MASTER_ITEM_LIST_FAILURE'

export const GET_MASTER_ITEM_DETAIL_REQUEST = '$MASTER_ITEM/GET_MASTER_ITEM_DETAIL_REQUEST'
export const GET_MASTER_ITEM_DETAIL_SUCCESS = '$MASTER_ITEM/GET_MASTER_ITEM_DETAIL_SUCCESS'
export const GET_MASTER_ITEM_DETAIL_FAILURE = '$MASTER_ITEM/GET_MASTER_ITEM_DETAIL_FAILURE'

export const GET_MASTER_ITEM_ALL_REQUEST = '$MASTER_ITEM/GET_MASTER_ITEM_ALL_REQUEST'
export const GET_MASTER_ITEM_ALL_SUCCESS = '$MASTER_ITEM/GET_MASTER_ITEM_ALL_SUCCESS'
export const GET_MASTER_ITEM_ALL_FAILURE = '$MASTER_ITEM/GET_MASTER_ITEM_ALL_FAILURE'
