workflows:
  react-native-android-dev:
    name: React Native App
    max_build_duration: 120
    instance_type: mac_mini
    cache:
      cache_paths:
        - ~/.gradle/caches
    environment:
      vars:
        PACKAGE_NAME: 'com.eplant'
      node: 14.17.0
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: development
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Setup node dependency
        script: |
          npm install
      - name: Setup keystore and service json
        script: |
          # Set up keystore
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
      - name: Init Android SDK
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Setup app config
        script: |
          yes | cp -r __config__/ci-config-dev.json __config__/config.json
          ./arvis export dev --initiate-only
      - name: Bump version
        script: |
          ./arvis bump patch
      - name: Build Android
        script: |
          npm run build
      - name: Push commit changes
        script: |
          ./arvis commit
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      # google_play:
      #   credentials: $GOOGLE_PLAY_KEY
      #   track: internal                      # Name of the track: internal, alpha, beta, production, internal app sharing, or your custom track name
      #   in_app_update_priority: 3         # Priority of the release (only set if in-app updates are supported): integer in range [0, 5]
      #   rollout_fraction: 0.999            # Rollout fraction (set only if releasing to a fraction of users): value between (0, 1)
      #   changes_not_sent_for_review: true # To be used ONLY if your app cannot be sent for review automatically *
      email:
        recipients:
          - rizki.aiman@arvis.id
          - feri.ferdinan@arvis.id
          - prieyuda.sustono@arvis.id
        notify:
          success: true
          failure: true
