export const CREATE_REQUEST_REQUEST = '$EPLANT_REQUEST/CREATE_REQUEST_REQUEST'
export const CREATE_REQUEST_SUCCESS = '$EPLANT_REQUEST/CREATE_REQUEST_SUCCESS'
export const CREATE_REQUEST_FAILURE = '$EPLANT_REQUEST/CREATE_REQUEST_FAILURE'
export const CREATE_OR_EDIT_REQUEST_CLEAR = '$EPLANT_REQUEST/CLEAR_FORM'

export const PROCESS_REQUEST_REQUEST = '$EPLANT_REQUEST/PROCESS_REQUEST_REQUEST'
export const PROCESS_REQUEST_SUCCESS = '$EPLANT_REQUEST/PROCESS_REQUEST_SUCCESS'
export const PROCESS_REQUEST_FAILURE = '$EPLANT_REQUEST/PROCESS_REQUEST_FAILURE'
export const PROCESS_REQUEST_CLEAR = '$EPLANT_REQUEST/CLEAR_FORM_PROCESS'

export const GET_MY_REQUEST_LIST_REQUEST = '$EPLANT_REQUEST/GET_MY_REQUEST_LIST_REQUEST'
export const GET_MY_REQUEST_LIST_SUCCESS = '$EPLANT_REQUEST/GET_MY_REQUEST_LIST_SUCCESS'
export const GET_MY_REQUEST_LIST_FAILURE = '$EPLANT_REQUEST/GET_MY_REQUEST_LIST_FAILURE'

export const GET_REQUEST_LIST_REQUEST = '$EPLANT_REQUEST/GET_REQUEST_LIST_REQUEST'
export const GET_REQUEST_LIST_SUCCESS = '$EPLANT_REQUEST/GET_REQUEST_LIST_SUCCESS'
export const GET_REQUEST_LIST_FAILURE = '$EPLANT_REQUEST/GET_REQUEST_LIST_FAILURE'

export const EDIT_REQUEST_REQUEST = '$EPLANT_REQUEST/EDIT_REQUEST_REQUEST'
export const EDIT_REQUEST_SUCCESS = '$EPLANT_REQUEST/EDIT_REQUEST_SUCCESS'
export const EDIT_REQUEST_FAILURE = '$EPLANT_REQUEST/EDIT_REQUEST_FAILURE'

export const DETAIL_REQUEST_REQUEST = '$EPLANT_REQUEST/DETAIL_REQUEST_REQUEST'
export const DETAIL_REQUEST_SUCCESS = '$EPLANT_REQUEST/DETAIL_REQUEST_SUCCESS'
export const DETAIL_REQUEST_FAILURE = '$EPLANT_REQUEST/DETAIL_REQUEST_FAILURE'

export const DELETE_REQUEST_REQUEST = '$EPLANT_REQUEST/DELETE_REQUEST_REQUEST'
export const DELETE_REQUEST_SUCCESS = '$EPLANT_REQUEST/DELETE_REQUEST_SUCCESS'
export const DELETE_REQUEST_FAILURE = '$EPLANT_REQUEST/DELETE_REQUEST_FAILURE'
export const DELETE_REQUEST_CLEAR = '$EPLANT_REQUEST/CLEAR_DELETE_STATE'
