export const CREATE_ITEM_REQUEST = '$ITEM/CREATE_ITEM_REQUEST'
export const CREATE_ITEM_SUCCESS = '$ITEM/CREATE_ITEM_SUCCESS'
export const CREATE_ITEM_FAILURE = '$ITEM/CREATE_ITEM_FAILURE'

export const EDIT_ITEM_REQUEST = '$ITEM/EDIT_ITEM_REQUEST'
export const EDIT_ITEM_SUCCESS = '$ITEM/EDIT_ITEM_SUCCESS'
export const EDIT_ITEM_FAILURE = '$ITEM/EDIT_ITEM_FAILURE'

export const CREATE_OR_EDIT_ITEM_CLEAR = '$ITEM/CREATE_OR_EDIT_ITEM_CLEAR'

export const DELETE_ITEM_REQUEST = '$ITEM/DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS = '$ITEM/DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAILURE = '$ITEM/DELETE_ITEM_FAILURE'
export const DELETE_ITEM_CLEAR = '$ITEM/DELETE_ITEM_CLEAR'

export const GET_ITEM_LIST_REQUEST = '$ITEM/GET_ITEM_LIST_REQUEST'
export const GET_ITEM_LIST_SUCCESS = '$ITEM/GET_ITEM_LIST_SUCCESS'
export const GET_ITEM_LIST_FAILURE = '$ITEM/GET_ITEM_LIST_FAILURE'

export const GET_ITEM_DETAIL_REQUEST = '$ITEM/GET_ITEM_DETAIL_REQUEST'
export const GET_ITEM_DETAIL_SUCCESS = '$ITEM/GET_ITEM_DETAIL_SUCCESS'
export const GET_ITEM_DETAIL_FAILURE = '$ITEM/GET_ITEM_DETAIL_FAILURE'

export const GET_ITEM_ALL_REQUEST = '$ITEM/GET_ITEM_ALL_REQUEST'
export const GET_ITEM_ALL_SUCCESS = '$ITEM/GET_ITEM_ALL_SUCCESS'
export const GET_ITEM_ALL_FAILURE = '$ITEM/GET_ITEM_ALL_FAILURE'
