export const OFFLINE_FETCH_REQUEST = '$OFFLINE_SYNC/OFFLINE_FETCH_REQUEST'
export const OFFLINE_FETCH_SUCCESS = '$OFFLINE_SYNC/OFFLINE_FETCH_SUCCESS'
export const OFFLINE_FETCH_FAILURE = '$OFFLINE_SYNC/OFFLINE_FETCH_FAILURE'
