export const GET_ALL_ROLE_REQUEST = '$EPLANT_ROLE/GET_ALL_ROLE_REQUEST'
export const GET_ALL_ROLE_SUCCESS = '$EPLANT_ROLE/GET_ALL_ROLE_SUCCESS'
export const GET_ALL_ROLE_FAILURE = '$EPLANT_ROLE/GET_ALL_ROLE_FAILURE'
