export const GET_SPB_LOCAL_LIST_REQUEST = '$SPB_LOCAL/GET_LIST_REQUEST'
export const GET_SPB_LOCAL_LIST_SUCCESS = '$SPB_LOCAL/GET_LIST_SUCCESS'
export const GET_SPB_LOCAL_LIST_FAILURE = '$SPB_LOCAL/GET_LIST_FAILURE'

export const GET_SPB_LOCAL_DETAIL_REQUEST = '$SPB_LOCAL/GET_DETAIL_REQUEST'
export const GET_SPB_LOCAL_DETAIL_SUCCESS = '$SPB_LOCAL/GET_DETAIL_SUCCESS'
export const GET_SPB_LOCAL_DETAIL_FAILURE = '$SPB_LOCAL/GET_DETAIL_FAILURE'

export const CREATE_SPB_LOCAL_REQUEST = '$SPB_LOCAL/CREATE_REQUEST'
export const CREATE_SPB_LOCAL_SUCCESS = '$SPB_LOCAL/CREATE_SUCCESS'
export const CREATE_SPB_LOCAL_FAILURE = '$SPB_LOCAL/CREATE_FAILURE'

export const UPDATE_SPB_LOCAL_REQUEST = '$SPB_LOCAL/UPDATE_REQUEST'
export const UPDATE_SPB_LOCAL_SUCCESS = '$SPB_LOCAL/UPDATE_SUCCESS'
export const UPDATE_SPB_LOCAL_FAILURE = '$SPB_LOCAL/UPDATE_FAILURE'

export const DELETE_SPB_LOCAL_REQUEST = '$SPB_LOCAL/DELETE_REQUEST'
export const DELETE_SPB_LOCAL_SUCCESS = '$SPB_LOCAL/DELETE_SUCCESS'
export const DELETE_SPB_LOCAL_FAILURE = '$SPB_LOCAL/DELETE_FAILURE'

export const CLEAR_SPB_LOCAL_FORM = '$SPB_LOCAL/CLEAR_FORM'
export const CLEAR_SPB_LOCAL_DELETE = '$SPB_LOCAL/CLEAR_DELETE'
export const CLEAR_SPB_LOCAL = '$SPB_LOCAL/CLEAR'
