export const CREATE_TONNAGE_PKS_REQUEST = '$TONNAGE_PKS/CREATE_TONNAGE_PKS_REQUEST'
export const CREATE_TONNAGE_PKS_SUCCESS = '$TONNAGE_PKS/CREATE_TONNAGE_PKS_SUCCESS'
export const CREATE_TONNAGE_PKS_FAILURE = '$TONNAGE_PKS/CREATE_TONNAGE_PKS_FAILURE'

export const EDIT_TONNAGE_PKS_REQUEST = '$TONNAGE_PKS/EDIT_TONNAGE_PKS_REQUEST'
export const EDIT_TONNAGE_PKS_SUCCESS = '$TONNAGE_PKS/EDIT_TONNAGE_PKS_SUCCESS'
export const EDIT_TONNAGE_PKS_FAILURE = '$TONNAGE_PKS/EDIT_TONNAGE_PKS_FAILURE'

export const DETAIL_TONNAGE_PKS_REQUEST = '$TONNAGE_PKS/DETAIL_TONNAGE_PKS_REQUEST'
export const DETAIL_TONNAGE_PKS_SUCCESS = '$TONNAGE_PKS/DETAIL_TONNAGE_PKS_SUCCESS'
export const DETAIL_TONNAGE_PKS_FAILURE = '$TONNAGE_PKS/DETAIL_TONNAGE_PKS_FAILURE'

export const CREATE_OR_EDIT_TONNAGE_PKS_CLEAR = '$TONNAGE_PKS/CREATE_OR_EDIT_TONNAGE_PKS_CLEAR'

export const DELETE_TONNAGE_PKS_REQUEST = '$TONNAGE_PKS/DELETE_TONNAGE_PKS_REQUEST'
export const DELETE_TONNAGE_PKS_SUCCESS = '$TONNAGE_PKS/DELETE_TONNAGE_PKS_SUCCESS'
export const DELETE_TONNAGE_PKS_FAILURE = '$TONNAGE_PKS/DELETE_TONNAGE_PKS_FAILURE'
export const DELETE_TONNAGE_PKS_CLEAR = '$TONNAGE_PKS/DELETE_TONNAGE_PKS_CLEAR'

export const GET_TONNAGE_PKS_LIST_REQUEST = '$TONNAGE_PKS/GET_TONNAGE_PKS_LIST_REQUEST'
export const GET_TONNAGE_PKS_LIST_SUCCESS = '$TONNAGE_PKS/GET_TONNAGE_PKS_LIST_SUCCESS'
export const GET_TONNAGE_PKS_LIST_FAILURE = '$TONNAGE_PKS/GET_TONNAGE_PKS_LIST_FAILURE'


export const GET_SPB_LIST_REQUEST = '$TONNAGE_PKS/GET_SPB_LIST_REQUEST'
export const GET_SPB_LIST_SUCCESS = '$TONNAGE_PKS/GET_SPB_LIST_SUCCESS'
export const GET_SPB_LIST_FAILURE = '$TONNAGE_PKS/GET_SPB_LIST_FAILURE'
