export const CREATE_TONNAGE_GARDEN_REQUEST = '$TONNAGE_GARDEN/CREATE_TONNAGE_GARDEN_REQUEST'
export const CREATE_TONNAGE_GARDEN_SUCCESS = '$TONNAGE_GARDEN/CREATE_TONNAGE_GARDEN_SUCCESS'
export const CREATE_TONNAGE_GARDEN_FAILURE = '$TONNAGE_GARDEN/CREATE_TONNAGE_GARDEN_FAILURE'

export const EDIT_TONNAGE_GARDEN_REQUEST = '$TONNAGE_GARDEN/EDIT_TONNAGE_GARDEN_REQUEST'
export const EDIT_TONNAGE_GARDEN_SUCCESS = '$TONNAGE_GARDEN/EDIT_TONNAGE_GARDEN_SUCCESS'
export const EDIT_TONNAGE_GARDEN_FAILURE = '$TONNAGE_GARDEN/EDIT_TONNAGE_GARDEN_FAILURE'

export const UPLOAD_TONNAGE_GARDEN_REQUEST = '$TONNAGE_GARDEN/UPLOAD_TONNAGE_GARDEN_REQUEST'
export const UPLOAD_TONNAGE_GARDEN_SUCCESS = '$TONNAGE_GARDEN/UPLOAD_TONNAGE_GARDEN_SUCCESS'
export const UPLOAD_TONNAGE_GARDEN_FAILURE = '$TONNAGE_GARDEN/UPLOAD_TONNAGE_GARDEN_FAILURE'

export const DETAIL_TONNAGE_GARDEN_REQUEST = '$TONNAGE_GARDEN/DETAIL_TONNAGE_GARDEN_REQUEST'
export const DETAIL_TONNAGE_GARDEN_SUCCESS = '$TONNAGE_GARDEN/DETAIL_TONNAGE_GARDEN_SUCCESS'
export const DETAIL_TONNAGE_GARDEN_FAILURE = '$TONNAGE_GARDEN/DETAIL_TONNAGE_GARDEN_FAILURE'

export const CREATE_OR_EDIT_TONNAGE_GARDEN_CLEAR = '$TONNAGE_GARDEN/FORM_CLEAR'

export const DELETE_TONNAGE_GARDEN_REQUEST = '$TONNAGE_GARDEN/DELETE_TONNAGE_GARDEN_REQUEST'
export const DELETE_TONNAGE_GARDEN_SUCCESS = '$TONNAGE_GARDEN/DELETE_TONNAGE_GARDEN_SUCCESS'
export const DELETE_TONNAGE_GARDEN_FAILURE = '$TONNAGE_GARDEN/DELETE_TONNAGE_GARDEN_FAILURE'
export const DELETE_TONNAGE_GARDEN_CLEAR = '$TONNAGE_GARDEN/DELETE_TONNAGE_GARDEN_CLEAR'

export const GET_TONNAGE_GARDEN_LIST_REQUEST = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_LIST_REQUEST'
export const GET_TONNAGE_GARDEN_LIST_SUCCESS = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_LIST_SUCCESS'
export const GET_TONNAGE_GARDEN_LIST_FAILURE = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_LIST_FAILURE'

export const GET_TONNAGE_GARDEN_ALL_REQUEST = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_ALL_REQUEST'
export const GET_TONNAGE_GARDEN_ALL_SUCCESS = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_ALL_SUCCESS'
export const GET_TONNAGE_GARDEN_ALL_FAILURE = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_ALL_FAILURE'

export const GET_TONNAGE_GARDEN_WITHOUT_PKS_REQUEST = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_WITHOUT_PKS_REQUEST'
export const GET_TONNAGE_GARDEN_WITHOUT_PKS_SUCCESS = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_WITHOUT_PKS_SUCCESS'
export const GET_TONNAGE_GARDEN_WITHOUT_PKS_FAILURE = '$TONNAGE_GARDEN/GET_TONNAGE_GARDEN_WITHOUT_PKS_FAILURE'
