export const GET_WAREHOUSE_LIST_REQUEST = '$EPLANT_WAREHOUSE/GET_WAREHOUSE_LIST_REQUEST'
export const GET_WAREHOUSE_LIST_SUCCESS = '$EPLANT_WAREHOUSE/GET_WAREHOUSE_LIST_SUCCESS'
export const GET_WAREHOUSE_LIST_FAILURE = '$EPLANT_WAREHOUSE/GET_WAREHOUSE_LIST_FAILURE'

export const GET_WAREHOUSE_DETAIL_REQUEST = '$EPLANT_WAREHOUSE/GET_WAREHOUSE_DETAIL_REQUEST'
export const GET_WAREHOUSE_DETAIL_SUCCESS = '$EPLANT_WAREHOUSE/GET_WAREHOUSE_DETAIL_SUCCESS'
export const GET_WAREHOUSE_DETAIL_FAILURE = '$EPLANT_WAREHOUSE/GET_WAREHOUSE_DETAIL_FAILURE'

export const APPROVE_WAREHOUSE_REQUEST = '$EPLANT_WAREHOUSE/APPROVE_WAREHOUSE_REQUEST'
export const APPROVE_WAREHOUSE_SUCCESS = '$EPLANT_WAREHOUSE/APPROVE_WAREHOUSE_SUCCESS'
export const APPROVE_WAREHOUSE_FAILURE = '$EPLANT_WAREHOUSE/APPROVE_WAREHOUSE_FAILURE'

export const POST_BPU_WAREHOUSE_REQUEST = '$EPLANT_WAREHOUSE/POST_BPU_WAREHOUSE_REQUEST'
export const POST_BPU_WAREHOUSE_SUCCESS = '$EPLANT_WAREHOUSE/POST_BPU_WAREHOUSE_SUCCESS'
export const POST_BPU_WAREHOUSE_FAILURE = '$EPLANT_WAREHOUSE/POST_BPU_WAREHOUSE_FAILURE'

export const CLEAR_FORM_APPROVE_WAREHOSUE = '$EPLANT_WAREHOUSE/CLEAR_FORM_APPROVE_WAREHOUSE_REQUEST'
export const CLEAR_FORM_POST_BPU_WAREHOSUE = '$EPLANT_WAREHOUSE/CLEAR_FORM_POST_BPU_WAREHOUSE_REQUEST'
