export const CREATE_ORGANIZATION_REQUEST = '$ORGANIZATION/CREATE_ORGANIZATION_REQUEST'
export const CREATE_ORGANIZATION_SUCCESS = '$ORGANIZATION/CREATE_ORGANIZATION_SUCCESS'
export const CREATE_ORGANIZATION_FAILURE = '$ORGANIZATION/CREATE_ORGANIZATION_FAILURE'

export const EDIT_ORGANIZATION_REQUEST = '$ORGANIZATION/EDIT_ORGANIZATION_REQUEST'
export const EDIT_ORGANIZATION_SUCCESS = '$ORGANIZATION/EDIT_ORGANIZATION_SUCCESS'
export const EDIT_ORGANIZATION_FAILURE = '$ORGANIZATION/EDIT_ORGANIZATION_FAILURE'

export const CREATE_OR_EDIT_ORGANIZATION_CLEAR = '$ORGANIZATION/CREATE_OR_EDIT_ORGANIZATION_CLEAR'

export const DELETE_ORGANIZATION_REQUEST = '$ORGANIZATION/DELETE_ORGANIZATION_REQUEST'
export const DELETE_ORGANIZATION_SUCCESS = '$ORGANIZATION/DELETE_ORGANIZATION_SUCCESS'
export const DELETE_ORGANIZATION_FAILURE = '$ORGANIZATION/DELETE_ORGANIZATION_FAILURE'
export const DELETE_ORGANIZATION_CLEAR = '$ORGANIZATION/DELETE_ORGANIZATION_CLEAR'

export const GET_ORGANIZATION_LIST_REQUEST = '$ORGANIZATION/GET_ORGANIZATION_LIST_REQUEST'
export const GET_ORGANIZATION_LIST_SUCCESS = '$ORGANIZATION/GET_ORGANIZATION_LIST_SUCCESS'
export const GET_ORGANIZATION_LIST_FAILURE = '$ORGANIZATION/GET_ORGANIZATION_LIST_FAILURE'

export const GET_ORGANIZATION_DETAIL_REQUEST = '$ORGANIZATION/GET_ORGANIZATION_DETAIL_REQUEST'
export const GET_ORGANIZATION_DETAIL_SUCCESS = '$ORGANIZATION/GET_ORGANIZATION_DETAIL_SUCCESS'
export const GET_ORGANIZATION_DETAIL_FAILURE = '$ORGANIZATION/GET_ORGANIZATION_DETAIL_FAILURE'

export const GET_ORGANIZATION_ALL_REQUEST = '$ORGANIZATION/GET_ORGANIZATION_ALL_REQUEST'
export const GET_ORGANIZATION_ALL_SUCCESS = '$ORGANIZATION/GET_ORGANIZATION_ALL_SUCCESS'
export const GET_ORGANIZATION_ALL_FAILURE = '$ORGANIZATION/GET_ORGANIZATION_ALL_FAILURE'

export const CLEAR_ORGANIZATION_ALL = '$ORGANIZATION/CLEAR_ORGANIZATION_ALL'
