export const REFRESH_MATERIALIZED_VIEWS_REQUEST = '$DASHBOARD/REFRESH_MATERIALIZED_VIEWS_REQUEST'
export const REFRESH_MATERIALIZED_VIEWS_SUCCESS = '$DASHBOARD/REFRESH_MATERIALIZED_VIEWS_SUCCESS'
export const REFRESH_MATERIALIZED_VIEWS_FAILURE = '$DASHBOARD/REFRESH_MATERIALIZED_VIEWS_FAILURE'

export const GET_BLOCKS_BY_DIVISION_REQUEST = '$DASHBOARD/GET_BLOCKS_BY_DIVISION_REQUEST'
export const GET_BLOCKS_BY_DIVISION_SUCCESS = '$DASHBOARD/GET_BLOCKS_BY_DIVISION_SUCCESS'
export const GET_BLOCKS_BY_DIVISION_FAILURE = '$DASHBOARD/GET_BLOCKS_BY_DIVISION_FAILURE'

export const GET_AKP_REPORT_REQUEST = '$DASHBOARD/GET_AKP_REPORT_REQUEST'
export const GET_AKP_REPORT_SUCCESS = '$DASHBOARD/GET_AKP_REPORT_SUCCESS'
export const GET_AKP_REPORT_FAILURE = '$DASHBOARD/GET_AKP_REPORT_FAILURE'

export const GET_AKP_PLANNING_REQUEST = '$DASHBOARD/GET_AKP_PLANNING_REQUEST'
export const GET_AKP_PLANNING_SUCCESS = '$DASHBOARD/GET_AKP_PLANNING_SUCCESS'
export const GET_AKP_PLANNING_FAILURE = '$DASHBOARD/GET_AKP_PLANNING_FAILURE'

export const GET_AKP_REALIZATION_REQUEST = '$DASHBOARD/GET_AKP_REALIZATION_REQUEST'
export const GET_AKP_REALIZATION_SUCCESS = '$DASHBOARD/GET_AKP_REALIZATION_SUCCESS'
export const GET_AKP_REALIZATION_FAILURE = '$DASHBOARD/GET_AKP_REALIZATION_FAILURE'

export const GET_RRP_REPORT_REQUEST = '$DASHBOARD/GET_RRP_REPORT_REQUEST'
export const GET_RRP_REPORT_SUCCESS = '$DASHBOARD/GET_RRP_REPORT_SUCCESS'
export const GET_RRP_REPORT_FAILURE = '$DASHBOARD/GET_RRP_REPORT_FAILURE'

export const GET_CROPBOOK_REPORT_REQUEST = '$DASHBOARD/GET_CROPBOOK_REPORT_REQUEST'
export const GET_CROPBOOK_REPORT_SUCCESS = '$DASHBOARD/GET_CROPBOOK_REPORT_SUCCESS'
export const GET_CROPBOOK_REPORT_FAILURE = '$DASHBOARD/GET_CROPBOOK_REPORT_FAILURE'

export const GET_RKB_TAKE_CARE_REQUEST = '$DASHBOARD/GET_RKB_TAKE_CARE_REQUEST'
export const GET_RKB_TAKE_CARE_SUCCESS = '$DASHBOARD/GET_RKB_TAKE_CARE_SUCCESS'
export const GET_RKB_TAKE_CARE_FAILURE = '$DASHBOARD/GET_RKB_TAKE_CARE_FAILURE'

export const GET_RKB_HARVEST_REQUEST = '$DASHBOARD/GET_RKB_HARVEST_REQUEST'
export const GET_RKB_HARVEST_SUCCESS = '$DASHBOARD/GET_RKB_HARVEST_SUCCESS'
export const GET_RKB_HARVEST_FAILURE = '$DASHBOARD/GET_RKB_HARVEST_FAILURE'

export const GET_AKP_BAR_CHART_REQUEST = '$DASHBOARD/GET_AKP_BAR_CHART_REQUEST'
export const GET_AKP_BAR_CHART_SUCCESS = '$DASHBOARD/GET_AKP_BAR_CHART_SUCCESS'
export const GET_AKP_BAR_CHART_FAILURE = '$DASHBOARD/GET_AKP_BAR_CHART_FAILURE'

export const GET_BPBKS_REPORT_REQUEST = '$DASHBOARD/GET_BPBKS_REPORT_REQUEST'
export const GET_BPBKS_REPORT_SUCCESS = '$DASHBOARD/GET_BPBKS_REPORT_SUCCESS'
export const GET_BPBKS_REPORT_FAILURE = '$DASHBOARD/GET_BPBKS_REPORT_FAILURE'

export const GET_YIELD_REPORT_REQUEST = '$DASHBOARD/GET_YIELD_REPORT_REQUEST'
export const GET_YIELD_REPORT_SUCCESS = '$DASHBOARD/GET_YIELD_REPORT_SUCCESS'
export const GET_YIELD_REPORT_FAILURE = '$DASHBOARD/GET_YIELD_REPORT_FAILURE'

export const GET_SEE_MATERIAL_RKB_REQUEST = '$DASHBOARD/GET_SEE_MATERIAL_RKB_REQUEST'
export const GET_SEE_MATERIAL_RKB_SUCCESS = '$DASHBOARD/GET_SEE_MATERIAL_RKB_SUCCESS'
export const GET_SEE_MATERIAL_RKB_FAILURE = '$DASHBOARD/GET_SEE_MATERIAL_RKB_FAILURE'

export const GET_BJR_REPORT_REQUEST = '$DASHBOARD/GET_BJR_REPORT_REQUEST'
export const GET_BJR_REPORT_SUCCESS = '$DASHBOARD/GET_BJR_REPORT_SUCCESS'
export const GET_BJR_REPORT_FAILURE = '$DASHBOARD/GET_BJR_REPORT_FAILURE'

export const GET_BPK_REPORT_REQUEST = '$DASHBOARD/GET_BPK_REPORT_REQUEST'
export const GET_BPK_REPORT_SUCCESS = '$DASHBOARD/GET_BPK_REPORT_SUCCESS'
export const GET_BPK_REPORT_FAILURE = '$DASHBOARD/GET_BPK_REPORT_FAILURE'

export const GET_BPK_MATERIAL_REPORT_REQUEST = '$DASHBOARD/GET_BPK_MATERIAL_REPORT_REQUEST'
export const GET_BPK_MATERIAL_REPORT_SUCCESS = '$DASHBOARD/GET_BPK_MATERIAL_REPORT_SUCCESS'
export const GET_BPK_MATERIAL_REPORT_FAILURE = '$DASHBOARD/GET_BPK_MATERIAL_REPORT_FAILURE'

export const GET_BMP_REPORT_REQUEST = '$DASHBOARD/GET_BMP_REPORT_REQUEST'
export const GET_BMP_REPORT_SUCCESS = '$DASHBOARD/GET_BMP_REPORT_SUCCESS'
export const GET_BMP_REPORT_FAILURE = '$DASHBOARD/GET_BMP_REPORT_FAILURE'

export const GET_EMPLOYEE_WAGES_REQUEST = '$DASHBOARD/GET_EMPLOYEE_WAGES_REQUEST'
export const GET_EMPLOYEE_WAGES_SUCCESS = '$DASHBOARD/GET_EMPLOYEE_WAGES_SUCCESS'
export const GET_EMPLOYEE_WAGES_FAILURE = '$DASHBOARD/GET_EMPLOYEE_WAGES_FAILURE'

export const GET_EMPLOYEE_WAGES_DEDUCTION_REQUEST = '$DASHBOARD/GET_EMPLOYEE_WAGES_DEDUCTION_REQUEST'
export const GET_EMPLOYEE_WAGES_DEDUCTION_SUCCESS = '$DASHBOARD/GET_EMPLOYEE_WAGES_DEDUCTION_SUCCESS'
export const GET_EMPLOYEE_WAGES_DEDUCTION_FAILURE = '$DASHBOARD/GET_EMPLOYEE_WAGES_DEDUCTION_FAILURE'

export const GET_PMA_REPORT_REQUEST = '$DASHBOARD/GET_PMA_REPORT_REQUEST'
export const GET_PMA_REPORT_SUCCESS = '$DASHBOARD/GET_PMA_REPORT_SUCCESS'
export const GET_PMA_REPORT_FAILURE = '$DASHBOARD/GET_PMA_REPORT_FAILURE'

export const GET_TONNAGE_GARDEN_REPORT_REQUEST = '$DASHBOARD/GET_TONNAGE_GARDEN_REPORT_REQUEST'
export const GET_TONNAGE_GARDEN_REPORT_SUCCESS = '$DASHBOARD/GET_TONNAGE_GARDEN_REPORT_SUCCESS'
export const GET_TONNAGE_GARDEN_REPORT_FAILURE = '$DASHBOARD/GET_TONNAGE_GARDEN_REPORT_FAILURE'

export const GET_TONNAGE_PKS_REPORT_REQUEST = '$DASHBOARD/GET_TONNAGE_PKS_REPORT_REQUEST'
export const GET_TONNAGE_PKS_REPORT_SUCCESS = '$DASHBOARD/GET_TONNAGE_PKS_REPORT_SUCCESS'
export const GET_TONNAGE_PKS_REPORT_FAILURE = '$DASHBOARD/GET_TONNAGE_PKS_REPORT_FAILURE'

export const GET_CHAPEL_REPORT_REQUEST = '$DASHBOARD/GET_CHAPEL_REPORT_REQUEST'
export const GET_CHAPEL_REPORT_SUCCESS = '$DASHBOARD/GET_CHAPEL_REPORT_SUCCESS'
export const GET_CHAPEL_REPORT_FAILURE = '$DASHBOARD/GET_CHAPEL_REPORT_FAILURE'

export const CLEAR_BLOCKS_BY_DIVISION = '$DASHBOARD/CLEAR_BLOCKS_BY_DIVISION'
export const CLEAR_MATERIALIZED_VIEWS = '$DASHBOARD/CLEAR_MATERIALIZED_VIEWS'
export const CLEAR_AKP_REPORT = '$DASHBOARD/CLEAR_AKP_REPORT'
export const CLEAR_AKP_PLANNING = '$DASHBOARD/CLEAR_AKP_PLANNING'
export const CLEAR_AKP_REALIZATION = '$DASHBOARD/CLEAR_AKP_REALIZATION'
export const CLEAR_AKP_BAR_CHART = '$DASHBOARD/CLEAR_AKP_BAR_CHART'
export const CLEAR_ALL_CHART = '$DASHBOARD/CLEAR_ALL_CHART'
export const CLEAR_RKB_TAKE_CARE_REPORT = '$DASHBOARD/CLEAR_RKB_TAKE_CARE_REPORT'
export const CLEAR_RKB_HARVEST_REPORT = '$DASHBOARD/CLEAR_RKB_HARVEST_REPORT'
export const CLEAR_BPBKS_REPORT = '$DASHBOARD/CLEAR_BPBKS_REPORT'
export const CLEAR_YIELD_REPORT = '$DASHBOARD/CLEAR_YIELD_REPORT'
export const CLEAR_SEE_MATERIAL_RKB_REPORT = '$DASHBOARD/CLEAR_SEE_MATERIAL_RKB_REPORT'
export const CLEAR_BJR_REPORT = '$DASHBOARD/CLEAR_BJR_REPORT'
export const CLEAR_EMPLOYEE_WAGES_REPORT = '$DASHBOARD/CLEAR_EMPLOYEE_WAGES_REPORT'
export const CLEAR_EMPLOYEE_WAGES_DEDUCTION_REPORT = '$DASHBOARD/CLEAR_EMPLOYEE_WAGES_DEDUCTION_REPORT'
export const CLEAR_RKB_MAYERIAL = '$DASHBOARD/CLEAR_RKB_MATERIAL'
export const CLEAR_PMA_REPORT = '$DASHBOARD/CLEAR_PMA_REPORT'
export const CLEAR_TONNAGE_GARDEN_REPORT = '$DASHBOARD/CLEAR_TONNAGE_GARDEN_REPORT'
export const CLEAR_TONNAGE_PKS_REPORT = '$DASHBOARD/CLEAR_TONNAGE_PKS_REPORT'
export const CLEAR_RRP_REPORT = '$DASHBOARD/CLEAR_RRP_REPORT'
export const CLEAR_CROPBOOK_REPORT = '$DASHBOARD/CLEAR_CROPBOOK_REPORT'
export const CLEAR_BPK_REPORT = '$DASHBOARD/CLEAR_BPK_REPORT'
export const CLEAR_BMP_REPORT = '$DASHBOARD/CLEAR_BMP_REPORT'
export const CLEAR_BPK_MATERIAL_REPORT = '$DASHBOARD/CLEAR_BPK_MATERIAL_REPORT'
export const CLEAR_CHAPEL_REPORT = '$DASHBOARD/CLEAR_CHAPEL_REPORT'

export const GET_ALL_CHART_REQUEST = '$DASHBOARD/GET_ALL_CHART_REQUEST'
export const GET_ALL_CHART_SUCCESS = '$DASHBOARD/GET_ALL_CHART_SUCCESS'
export const GET_ALL_CHART_FAILURE = '$DASHBOARD/GET_ALL_CHART_FAILURE'

export const GET_PRODUCTION_ORGANIZATION_REQUEST = '$DASHBOARD/GET_PRODUCTION_ORGANIZATION_REQUEST'
export const GET_PRODUCTION_ORGANIZATION_SUCCESS = '$DASHBOARD/GET_PRODUCTION_ORGANIZATION_SUCCESS'
export const GET_PRODUCTION_ORGANIZATION_FAILURE = '$DASHBOARD/GET_PRODUCTION_ORGANIZATION_FAILURE'

export const GET_PRODUCTION_ORGANIZATION_CHART_REQUEST = '$DASHBOARD/GET_PRODUCTION_ORGANIZATION_CHART_REQUEST'
export const GET_PRODUCTION_ORGANIZATION_CHART_SUCCESS = '$DASHBOARD/GET_PRODUCTION_ORGANIZATION_CHART_SUCCESS'
export const GET_PRODUCTION_ORGANIZATION_CHART_FAILURE = '$DASHBOARD/GET_PRODUCTION_ORGANIZATION_CHART_FAILURE'
