export const CREATE_BLOCK_REQUEST = '$EPLANT_BLOCK/CREATE_BLOCK_REQUEST'
export const CREATE_BLOCK_SUCCESS = '$EPLANT_BLOCK/CREATE_BLOCK_SUCCESS'
export const CREATE_BLOCK_FAILURE = '$EPLANT_BLOCK/CREATE_BLOCK_FAILURE'

export const EDIT_BLOCK_REQUEST = '$EPLANT_BLOCK/EDIT_BLOCK_REQUEST'
export const EDIT_BLOCK_SUCCESS = '$EPLANT_BLOCK/EDIT_BLOCK_SUCCESS'
export const EDIT_BLOCK_FAILURE = '$EPLANT_BLOCK/EDIT_BLOCK_FAILURE'

export const GET_BLOCK_LIST_REQUEST = '$EPLANT_BLOCK/GET_BLOCK_LIST_REQUEST'
export const GET_BLOCK_LIST_SUCCESS = '$EPLANT_BLOCK/GET_BLOCK_LIST_SUCCESS'
export const GET_BLOCK_LIST_FAILURE = '$EPLANT_BLOCK/GET_BLOCK_LIST_FAILURE'

export const GET_BLOCK_FOREMAN_REQUEST = '$EPLANT_BLOCK/GET_BLOCKS_FOREMAN_REQUEST'
export const GET_BLOCK_FOREMAN_SUCCESS = '$EPLANT_BLOCK/GET_BLOCKS_FOREMAN_SUCCESS'
export const GET_BLOCK_FOREMAN_FAILURE = '$EPLANT_BLOCK/GET_BLOCKS_FOREMAN_FAILURE'

export const GET_ALL_FOREMAN_REQUEST = '$EPLANT_BLOCK/GET_ALL_FOREMAN_REQUEST'
export const GET_ALL_FOREMAN_SUCCESS = '$EPLANT_BLOCK/GET_ALL_FOREMAN_SUCCESS'
export const GET_ALL_FOREMAN_FAILURE = '$EPLANT_BLOCK/GET_ALL_FOREMAN_FAILURE'

export const GET_ALL_BLOCK_REQUEST = '$EPLANT_BLOCK/GET_ALL_BLOCK_REQUEST'
export const GET_ALL_BLOCK_SUCCESS = '$EPLANT_BLOCK/GET_ALL_BLOCK_SUCCESS'
export const GET_ALL_BLOCK_FAILURE = '$EPLANT_BLOCK/GET_ALL_BLOCK_FAILURE'

export const DELETE_BLOCK_REQUEST = '$EPLANT_BLOCK/DELETE_BLOCK_REQUEST'
export const DELETE_BLOCK_SUCCESS = '$EPLANT_BLOCK/DELETE_BLOCK_SUCCESS'
export const DELETE_BLOCK_FAILURE = '$EPLANT_BLOCK/DELETE_BLOCK_FAILURE'

export const DETAIL_BLOCK_REQUEST = '$EPLANT_BLOCK/DETAIL_BLOCK_REQUEST'
export const DETAIL_BLOCK_SUCCESS = '$EPLANT_BLOCK/DETAIL_BLOCK_SUCCESS'
export const DETAIL_BLOCK_FAILURE = '$EPLANT_BLOCK/DETAIL_BLOCK_FAILURE'

export const CREATE_OR_EDIT_BLOCK_CLEAR = '$EPLANT_BLOCK/CREATE_OR_EDIT_BLOCK_CLEAR'
export const DELETE_BLOCK_CLEAR = '$EPLANT_BLOCK/CLEAR_DELETE_STATE'
