export const CREATE_BPBKS_REQUEST = '$BPBKS/CREATE_BPBKS_REQUEST'
export const CREATE_BPBKS_SUCCESS = '$BPBKS/CREATE_BPBKS_SUCCESS'
export const CREATE_BPBKS_FAILURE = '$BPBKS/CREATE_BPBKS_FAILURE'

export const EDIT_BPBKS_REQUEST = '$BPBKS/EDIT_BPBKS_REQUEST'
export const EDIT_BPBKS_SUCCESS = '$BPBKS/EDIT_BPBKS_SUCCESS'
export const EDIT_BPBKS_FAILURE = '$BPBKS/EDIT_BPBKS_FAILURE'

export const DETAIL_BPBKS_REQUEST = '$BPBKS/DETAIL_BPBKS_REQUEST'
export const DETAIL_BPBKS_SUCCESS = '$BPBKS/DETAIL_BPBKS_SUCCESS'
export const DETAIL_BPBKS_FAILURE = '$BPBKS/DETAIL_BPBKS_FAILURE'

export const GET_ALL_BPBKS_REQUEST = '$BPBKS/GET_ALL_BPBKS_REQUEST'
export const GET_ALL_BPBKS_SUCCESS = '$BPBKS/GET_ALL_BPBKS_SUCCESS'
export const GET_ALL_BPBKS_FAILURE = '$BPBKS/GET_ALL_BPBKS_FAILURE'

export const SYNC_BPBKS_REQUEST = '$BPBKS/SYNC_BPBKS_REQUEST'
export const SYNC_BPBKS_SUCCESS = '$BPBKS/SYNC_BPBKS_SUCCESS'
export const SYNC_BPBKS_FAILURE = '$BPBKS/SYNC_BPBKS_FAILURE'

export const CREATE_OR_EDIT_BPBKS_CLEAR = '$BPBKS/CREATE_OR_EDIT_BPBKS_CLEAR'

export const DELETE_BPBKS_REQUEST = '$BPBKS/DELETE_BPBKS_REQUEST'
export const DELETE_BPBKS_SUCCESS = '$BPBKS/DELETE_BPBKS_SUCCESS'
export const DELETE_BPBKS_FAILURE = '$BPBKS/DELETE_BPBKS_FAILURE'
export const DELETE_BPBKS_CLEAR = '$BPBKS/DELETE_BPBKS_CLEAR'

export const GET_BPBKS_LIST_REQUEST = '$BPBKS/GET_BPBKS_LIST_REQUEST'
export const GET_BPBKS_LIST_SUCCESS = '$BPBKS/GET_BPBKS_LIST_SUCCESS'
export const GET_BPBKS_LIST_FAILURE = '$BPBKS/GET_BPBKS_LIST_FAILURE'

export const ADD_BPBKS_TEMP = '$BPBKS/ADD_BPBKS_TEMP'
export const EDIT_BPBKS_TEMP = '$BPBKS/EDIT_BPBKS_TEMP'
export const DELETE_BPBKS_TEMP = '$BPBKS/DELETE_BPBKS_TEMP'
export const DELETE_BPBKS_EMPLOYEE_TEMP = '$BPBKS/DELETE_BPBKS_EMPLOYEE_TEMP'
export const UPDATE_BPBKS_TEMP_STATUS = '$BPBKS/UPDATE_BPBKS_TEMP_STATUS'

export const CLEAR_DRAFT_BPBKS_REQUEST = '$BPBKS/CLEAR_DRAFT_BPBKS_REQUEST'
export const CLEAR_DRAFT_BPBKS_SUCCESS = '$BPBKS/CLEAR_DRAFT_BPBKS_SUCCESS'
export const CLEAR_DRAFT_BPBKS_FAILURE = '$BPBKS/CLEAR_DRAFT_BPBKS_FAILURE'

export const CLEAR_BPBKS_ALL = '$BPBKS/CLEAR_BPBKS_ALL'
