export const CREATE_FIELD_REPORT_REQUEST = '$EPLANT_FIELD_REPORT/CREATE_FIELD_REPORT_REQUEST'
export const CREATE_FIELD_REPORT_SUCCESS = '$EPLANT_FIELD_REPORT/CREATE_FIELD_REPORT_SUCCESS'
export const CREATE_FIELD_REPORT_FAILURE = '$EPLANT_FIELD_REPORT/CREATE_FIELD_REPORT_FAILURE'
export const CREATE_OR_EDIT_FIELD_REPORT_CLEAR = '$EPLANT_FIELD_REPORT/CLEAR_FORM'

export const GET_FIELD_REPORT_LIST_REQUEST = '$EPLANT_FIELD_REPORT/GET_FIELD_REPORT_LIST_REQUEST'
export const GET_FIELD_REPORT_LIST_SUCCESS = '$EPLANT_FIELD_REPORT/GET_FIELD_REPORT_LIST_SUCCESS'
export const GET_FIELD_REPORT_LIST_FAILURE = '$EPLANT_FIELD_REPORT/GET_FIELD_REPORT_LIST_FAILURE'

export const EDIT_FIELD_REPORT_REQUEST = '$EPLANT_FIELD_REPORT/EDIT_FIELD_REPORT_REQUEST'
export const EDIT_FIELD_REPORT_SUCCESS = '$EPLANT_FIELD_REPORT/EDIT_FIELD_REPORT_SUCCESS'
export const EDIT_FIELD_REPORT_FAILURE = '$EPLANT_FIELD_REPORT/EDIT_FIELD_REPORT_FAILURE'

export const DETAIL_FIELD_REPORT_REQUEST = '$EPLANT_FIELD_REPORT/DETAIL_FIELD_REPORT_REQUEST'
export const DETAIL_FIELD_REPORT_SUCCESS = '$EPLANT_FIELD_REPORT/DETAIL_FIELD_REPORT_SUCCESS'
export const DETAIL_FIELD_REPORT_FAILURE = '$EPLANT_FIELD_REPORT/DETAIL_FIELD_REPORT_FAILURE'

export const DELETE_FIELD_REPORT_REQUEST = '$EPLANT_FIELD_REPORT/DELETE_FIELD_REPORT_REQUEST'
export const DELETE_FIELD_REPORT_SUCCESS = '$EPLANT_FIELD_REPORT/DELETE_FIELD_REPORT_SUCCESS'
export const DELETE_FIELD_REPORT_FAILURE = '$EPLANT_FIELD_REPORT/DELETE_FIELD_REPORT_FAILURE'
export const DELETE_FIELD_REPORT_CLEAR = '$EPLANT_FIELD_REPORT/CLEAR_DELETE_STATE'

export const DELETE_FILE_FIELD_REPORT_REQUEST = '$EPLANT_FIELD_REPORT/DELETE_FILE_FIELD_REPORT_REQUEST'
export const DELETE_FILE_FIELD_REPORT_SUCCESS = '$EPLANT_FIELD_REPORT/DELETE_FILE_FIELD_REPORT_SUCCESS'
export const DELETE_FILE_FIELD_REPORT_FAILURE = '$EPLANT_FIELD_REPORT/DELETE_FILE_FIELD_REPORT_FAILURE'
export const DELETE_FILE_FIELD_REPORT_CLEAR = '$EPLANT_FIELD_REPORT/CLEAR_FILE_DELETE_STATE'
