export const LOGIN_REQUEST = '$AUTH/LOGIN_REQUEST'
export const LOGIN_SUCCESS = '$AUTH/LOGIN_SUCCESS'
export const LOGIN_FAILURE = '$AUTH/LOGIN_FAILURE'

export const FORGOT_PASSWORD_REQUEST = '$AUTH/FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = '$AUTH/FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = '$AUTH/FORGOT_PASSWORD_FAILURE'

export const CHANGE_PASSWORD_REQUEST = '$AUTH/CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = '$AUTH/CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = '$AUTH/CHANGE_PASSWORD_FAILURE'

export const LOGOUT_REQUEST = '$AUTH/LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = '$AUTH/LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = '$AUTH/LOGOUT_FAILURE'

export const GET_ALL_USER_REQUEST = '$EPLANT_USER/GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = '$EPLANT_USER/GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILURE = '$EPLANT_USER/GET_ALL_USER_FAILURE'

export const GET_ALL_USER_COST_REQUEST = '$EPLANT_USER/GET_ALL_USER_COST_REQUEST'
export const GET_ALL_USER_COST_SUCCESS = '$EPLANT_USER/GET_ALL_USER_COST_SUCCESS'
export const GET_ALL_USER_COST_FAILURE = '$EPLANT_USER/GET_ALL_USER_COST_FAILURE'

export const GET_CURRENT_USER_REQUEST = '$EPLANT_USER/GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = '$EPLANT_USER/GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAILURE = '$EPLANT_USER/GET_CURRENT_USER_FAILURE'

export const CLEAR_USER_PROFILE = 'arvisAuth/CLEAR_USER_PROFILE'
export const CLEAR_USER_CREDENTIAL = 'arvisAuth/CLEAR_USER_CREDENTIAL'

export const LOGOUT = 'arvisAuth/LOGOUT'

export const UPLOAD_PROFILE_PICTURE_REQUEST = '$EPLANT_USER/UPLOAD_PROFILE_PICTURE_REQUEST'
export const UPLOAD_PROFILE_PICTURE_SUCCESS = '$EPLANT_USER/UPLOAD_PROFILE_PICTURE_SUCCESS'
export const UPLOAD_PROFILE_PICTURE_FAILURE = '$EPLANT_USER/UPLOAD_PROFILE_PICTURE_FAILURE'

export const UPLOAD_PROFILE_PICTURE_CLEAR = '$EPLANT_USER/UPLOAD_PROFILE_PICTURE_CLEAR'

export const ADD_OR_UPDATE_EMAIL_REQUEST = '$EPLANT_USER/ADD_OR_UPDATE_EMAIL_REQUEST'
export const ADD_OR_UPDATE_EMAIL_SUCCESS = '$EPLANT_USER/ADD_OR_UPDATE_EMAIL_SUCCESS'
export const ADD_OR_UPDATE_EMAIL_FAILURE = '$EPLANT_USER/ADD_OR_UPDATE_EMAIL_FAILURE'

export const ADD_OR_UPDATE_EMAIL_CLEAR = '$EPLANT_USER/ADD_OR_UPDATE_EMAIL_CLEAR'

export const UPDATE_PASSWORD_REQUEST = '$EPLANT_USER/UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = '$EPLANT_USER/UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAILURE = '$EPLANT_USER/UPDATE_PASSWORD_FAILURE'

export const UPDATE_PASSWORD_CLEAR = '$EPLANT_USER/UPDATE_PASSWORD_CLEAR'

export const FORGOT_PASSWORD_CLEAR = '$EPLANT_USER/FORGOT_PASSWORD_CLEAR'

export const RESET_PASSWORD_CLEAR = '$EPLANT_USER/RESET_PASSWORD_CLEAR'
export const LOGIN_FORM_CLEAR = 'arvisAuth/LOGIN_FORM_CLEAR'

export const SYNC_MASTER_DATA_REQUEST = '$EPLANT_USER/SYNC_MASTER_DATA_REQUEST'
export const SYNC_MASTER_DATA_SUCCESS = '$EPLANT_USER/SYNC_MASTER_DATA_SUCCESS'
export const SYNC_MASTER_DATA_FAILURE = '$EPLANT_USER/SYNC_MASTER_DATA_FAILURE'
