export const CREATE_AKP_REQUEST = '$AKP/CREATE_AKP_REQUEST'
export const CREATE_AKP_SUCCESS = '$AKP/CREATE_AKP_SUCCESS'
export const CREATE_AKP_FAILURE = '$AKP/CREATE_AKP_FAILURE'

export const EDIT_AKP_REQUEST = '$AKP/EDIT_AKP_REQUEST'
export const EDIT_AKP_SUCCESS = '$AKP/EDIT_AKP_SUCCESS'
export const EDIT_AKP_FAILURE = '$AKP/EDIT_AKP_FAILURE'

export const DETAIL_AKP_REQUEST = '$AKP/DETAIL_AKP_REQUEST'
export const DETAIL_AKP_SUCCESS = '$AKP/DETAIL_AKP_SUCCESS'
export const DETAIL_AKP_FAILURE = '$AKP/DETAIL_AKP_FAILURE'

export const SYNC_AKP_REQUEST = '$AKP/SYNC_AKP_REQUEST'
export const SYNC_AKP_SUCCESS = '$AKP/SYNC_AKP_SUCCESS'
export const SYNC_AKP_FAILURE = '$AKP/SYNC_AKP_FAILURE'

export const CREATE_OR_EDIT_AKP_CLEAR = '$AKP/CREATE_OR_EDIT_AKP_CLEAR'

export const DELETE_AKP_REQUEST = '$AKP/DELETE_AKP_REQUEST'
export const DELETE_AKP_SUCCESS = '$AKP/DELETE_AKP_SUCCESS'
export const DELETE_AKP_FAILURE = '$AKP/DELETE_AKP_FAILURE'
export const DELETE_AKP_CLEAR = '$AKP/DELETE_AKP_CLEAR'

export const GET_AKP_LIST_REQUEST = '$AKP/GET_AKP_LIST_REQUEST'
export const GET_AKP_LIST_SUCCESS = '$AKP/GET_AKP_LIST_SUCCESS'
export const GET_AKP_LIST_FAILURE = '$AKP/GET_AKP_LIST_FAILURE'

export const GET_ALL_AKP_REQUEST = '$AKP/GET_ALL_AKP_REQUEST'
export const GET_ALL_AKP_SUCCESS = '$AKP/GET_ALL_AKP_SUCCESS'
export const GET_ALL_AKP_FAILURE = '$AKP/GET_ALL_AKP_FAILURE'

export const ADD_AKP_TEMP = '$AKP/ADD_AKP_TEMP'
export const EDIT_AKP_TEMP = '$AKP/EDIT_AKP_TEMP'
export const DELETE_AKP_TEMP = '$AKP/DELETE_AKP_TEMP'

export const CLEAR_AKP_TEMP_REQUEST = '$AKP/CLEAR_AKP_DRAFT_REQUEST'
export const CLEAR_AKP_TEMP_SUCCESS = '$AKP/CLEAR_AKP_DRAFT_SUCCESS'
export const CLEAR_AKP_TEMP_FAILURE = '$AKP/CLEAR_AKP_DRAFT_FAILURE'
