export const GET_DIVISION_LIST_REQUEST = '$EPLANT_DIVISION/GET_DIVISION_LIST_REQUEST'
export const GET_DIVISION_LIST_SUCCESS = '$EPLANT_DIVISION/GET_DIVISION_LIST_SUCCESS'
export const GET_DIVISION_LIST_FAILURE = '$EPLANT_DIVISION/GET_DIVISION_LIST_FAILURE'

export const GET_ALL_DIVISION_REQUEST = '$EPLANT_DIVISION/GET_ALL_DIVISION_REQUEST'
export const GET_ALL_DIVISION_SUCCESS = '$EPLANT_DIVISION/GET_ALL_DIVISION_SUCCESS'
export const GET_ALL_DIVISION_FAILURE = '$EPLANT_DIVISION/GET_ALL_DIVISION_FAILURE'

export const CREATE_DIVISION_REQUEST = '$EPLANT_DIVISION/CREATE_DIVISION_REQUEST'
export const CREATE_DIVISION_SUCCESS = '$EPLANT_DIVISION/CREATE_DIVISION_SUCCESS'
export const CREATE_DIVISION_FAILURE = '$EPLANT_DIVISION/CREATE_DIVISION_FAILURE'

export const EDIT_DIVISION_REQUEST = '$EPLANT_DIVISION/EDIT_DIVISION_REQUEST'
export const EDIT_DIVISION_SUCCESS = '$EPLANT_DIVISION/EDIT_DIVISION_SUCCESS'
export const EDIT_DIVISION_FAILURE = '$EPLANT_DIVISION/EDIT_DIVISION_FAILURE'

export const DELETE_DIVISION_REQUEST = '$EPLANT_DIVISION/DELETE_DIVISION_REQUEST'
export const DELETE_DIVISION_SUCCESS = '$EPLANT_DIVISION/DELETE_DIVISION_SUCCESS'
export const DELETE_DIVISION_FAILURE = '$EPLANT_DIVISION/DELETE_DIVISION_FAILURE'

export const DETAIL_DIVISION_REQUEST = '$EPLANT_DIVISION/DETAIL_DIVISION_REQUEST'
export const DETAIL_DIVISION_SUCCESS = '$EPLANT_DIVISION/DETAIL_DIVISION_SUCCESS'
export const DETAIL_DIVISION_FAILURE = '$EPLANT_DIVISION/DETAIL_DIVISION_FAILURE'

export const CREATE_OR_EDIT_DIVISION_CLEAR = '$EPLANT_DIVISION/CLEAR_FORM'
export const DELETE_DIVISION_CLEAR = '$EPLANT_DIVISION/CLEAR_DELETE_STATE'
