export default class Routes {
  static LOGIN = '/app/login'
  static REGISTRATION = '/app/registration'
  static FORGOT_PASSWORD = '/app/forgot-password'
  static RESET_PASSWORD = '/app/reset-password'

  static BOTTOM_TAB = '/app/tab'
  static HOME_PAGE = 'app/home-page'
  static HOME_STACK = 'app/home-stack'
  static DASHBOARD_STACK = 'app/dashboard-stack'
  static PROFILE_STACK = 'app/profile-stack'
  static DASHBOARD = '/app/dashboard'
  static DASHBOARD_PRODUCTION_ORGANIZATION = '/app/dashboard/production-organization'
  static MORE = '/app/more'

  static MASTER_DATA = 'app/home-stack/master-data'
  static PLAN = 'app/home-stack/plan'
  static HARVEST = 'app/home-stack/harvest'
  static ATTENDANCE = 'app/home-stack/attendance'
  static TAKE_CARE = 'app/home-stack/take-care'
  static REPORT = 'app/home-stack/report'
  static REQUEST = 'app/home-stack/request'
  static APPROVAL = 'app/home-stack/approval'
  static NOTIFICATION = 'app/home-stack/notification'

  static DIVISION_LIST = 'app/home-stack/master-data/division-list'
  static DIVISION_FORM = 'app/home-stack/master-data/division-form'
  static DIVISION_UPDATE = 'app/home-stack/master-data/division-update'
  static DIVISION_DETAIL = 'app/home-stack/master-data/division-detail'

  static BLOCK_LIST = 'app/home-stack/master-data/block-list'
  static BLOCK_FORM = 'app/home-stack/master-data/block-create'
  static BLOCK_DETAIL = 'app/home-stack/master-data/block-detail'

  static RAW_MATERIAL_LIST = 'app/home-stack/master-data/raw-material-list'
  static RAW_MATERIAL_FORM = 'app/home-stack/master-data/raw-material-form'
  static RAW_MATERIAL_DETAIL = 'app/home-stack/master-data/raw-material-detail'

  static RAW_MATERIAL_PURCHASEMENT_FORM = 'app/home-stack/master-data/raw-material-purchasement-form'
  static RAW_MATERIAL_RECEPTION_FORM = 'app/home-stack/master-data/raw-material-reception-form'

  static MAPS_PREVIEW = 'app/home-stack/master-data/maps-preview'

  static PROFILE = '/app/profile'
  static EDIT_PROFILE = '/app/profile-edit'

  static PROFILE_PAGE = '/app/profile-stack/profile-page'
  static APPROVER = Routes.PROFILE + '/approver'
  static WORKING_AREA = Routes.PROFILE + '/working-area'
  static CHANGE_PROFILE = Routes.PROFILE + '/change-profile'
  static CHANGE_PROFILE_PASSWORD = Routes.PROFILE + '/change-profile-password'
  static ADD_CHANGE_EMAIL = Routes.PROFILE + '/add-change-email'

  static ORGANIZATION_DETAIL = '/app/master-data/organization-detail'
  static ORGANIZATION_LIST = '/app/master-data/organization-list'
  static ORGANIZATION_FORM = '/app/master-data/organization-form'

  static TPH_LIST = '/app/master-data/tph-list'
  static TPH_FORM = '/app/master-data/tph-form'

  static TOOLS_AND_EQUIPMENT_LIST = '/app/master-data/tools-and-equipment-list'

  static CATEGORY_ITEM_LIST = Routes.TOOLS_AND_EQUIPMENT_LIST + '/category-item-list'
  static CATEGORY_ITEM_FORM = Routes.TOOLS_AND_EQUIPMENT_LIST + '/category-item-form'
  static CATEGORY_ITEM_DETAIL = Routes.TOOLS_AND_EQUIPMENT_LIST + '/category-item-detail'

  static MASTER_ITEM_LIST = Routes.TOOLS_AND_EQUIPMENT_LIST + '/master-item-list'
  static MASTER_ITEM_FORM = Routes.TOOLS_AND_EQUIPMENT_LIST + '/master-item-form'
  static MASTER_ITEM_DETAIL = Routes.TOOLS_AND_EQUIPMENT_LIST + '/master-item-detail'

  static ITEM_LIST = Routes.TOOLS_AND_EQUIPMENT_LIST + '/item-list'
  static ITEM_FORM = Routes.TOOLS_AND_EQUIPMENT_LIST + '/item-form'
  static ITEM_DETAIL = Routes.TOOLS_AND_EQUIPMENT_LIST + '/item-detail'
  static ITEM_DETAIL_TRANSPORTATION = Routes.TOOLS_AND_EQUIPMENT_LIST + '/item-detail-transportation'

  static DAILY_ACTIVITY_FORM = Routes.TOOLS_AND_EQUIPMENT_LIST + '/daily-activity-form'
  static DAILY_ACTIVITY_DETAIL = Routes.TOOLS_AND_EQUIPMENT_LIST + '/daily-activity-detail'
  static MAINTENANCE_FORM = Routes.TOOLS_AND_EQUIPMENT_LIST + '/maintenance-form'
  static MAINTENANCE_DETAIL = Routes.TOOLS_AND_EQUIPMENT_LIST + '/maintenance-detail'

  static TAXATION_FILTER = 'app/home-stack/plan/taxation-filter'
  static TAXATION_LIST = 'app/home-stack/plan/taxation-list'
  static TAXATION_FORM = 'app/home-stack/plan/taxation-form'

  static AKP_FILTER = 'app/home-stack/plan/akp-filter'
  static AKP_LIST = 'app/home-stack/plan/akp-list'
  static AKP_FORM = 'app/home-stack/plan/akp-form'
  static AKP_DETAIL = 'app/home-stack/plan/akp-detail'
  static TAXATION_DETAIL = 'app/home-stack/plan/taxation-detail'

  static CENSUS_FILTER = 'app/home-stack/plan/census-filter'
  static CENSUS_LIST = 'app/home-stack/plan/census-list'
  static CENSUS_FORM = 'app/home-stack/plan/census-form'
  static CENSUS_DETAIL = 'app/home-stack/plan/census-detail'

  static RKH_HARVEST_FORM = 'app/home-stack/plan/rkh-harvest-form'
  static RKH_HARVEST_FORM_EMPLOYEE = 'app/home-stack/plan/rkh-harvest-form-employee'
  static RKH_HARVEST_DETAIL = 'app/home-stack/plan/rkh-harvest-detail'
  static RKH_FILTER = 'app/home-stack/plan/rkh-filter'
  static RKH_LIST = 'app/home-stack/plan/rkh-list'
  static RKH_FORM = 'app/home-stack/plan/rkh-form'
  static RKH_DETAIL = 'app/home-stack/plan/rkh-detail'

  static RKH_LIST_TAB = 'app/home-stack/plan/rkh-list-tab'

  static RKH_TAKE_CARE_FORM = 'app/home-stack/plan/rkh-take-care-form'
  static RKH_TAKE_CARE_DETAIL = 'app/home-stack/plan/rkh-take-care-detail'
  static RKH_TAKE_CARE_FORM_ITEM = 'app/home-stack/plan/rkh-take-care-form-item'
  static RKH_TAKE_CARE_FORM_MATERIAL = 'app/home-stack/plan/rkh-take-care-form-material'

  static RKH_LIST_EMPLOYEE = 'app/home-stack/plan/rkh-list-employee'

  static ATTENDANCE_FILTER = Routes.ATTENDANCE + '/attendance-filter'
  static ATTENDANCE_LIST = Routes.ATTENDANCE + '/attendance-list'
  static ATTENDANCE_EMPLOYEE_FORM = Routes.ATTENDANCE + '/attendance-employee-form'
  static ATTENDANCE_FILE_FORM = Routes.ATTENDANCE + '/attendance-file-form'
  static ATTENDANCE_DETAIL = Routes.ATTENDANCE + '/attendance-detail'

  static BKM_FILTER = Routes.HARVEST + '/bkm-filter'
  static BKM_LIST = Routes.HARVEST + '/bkm-list'
  static BKM_FORM = Routes.HARVEST + '/bkm-form'
  static BKM_DETAIL = Routes.HARVEST + '/bkm-detail'
  static BKM_EMPLOYEE_DETAIL = Routes.HARVEST + '/bkm-employee-detail'
  static PMB_FILTER = Routes.HARVEST + '/pmb-filter'
  static PMA_FILTER = Routes.HARVEST + '/pma-filter'
  static PMA_LIST = Routes.HARVEST + '/pma-list'
  static PMA_FORM = Routes.HARVEST + '/pma-form'
  static PMA_DETAIL = Routes.HARVEST + '/pma-detail'
  static PMA_PREVIEW = Routes.HARVEST + '/pma-preview'

  static TONNAGE_GARDEN_LIST = Routes.HARVEST + '/tonnage-garden-list'
  static TONNAGE_GARDEN_FORM = Routes.HARVEST + '/tonnage-garden-form'
  static TONNAGE_GARDEN_UPLOAD_FILE = Routes.HARVEST + '/tonnage-garden-upload-file'
  static TONNAGE_GARDEN_DETAIL = Routes.HARVEST + '/tonnage-garden-detail'
  static TONNAGE_PKS_LIST = Routes.HARVEST + '/tonnage-pks-list'
  static TONNAGE_PKS_FORM = Routes.HARVEST + '/tonnage-pks-form'
  static TONNAGE_PKS_DETAIL = Routes.HARVEST + '/tonnage-pks-detail'

  static MONITORING_TPH_FILTER = Routes.HARVEST + '/monitoring-tph-filter'
  static MONITORING_TPH_LIST = Routes.HARVEST + '/monitoring-tph-list'
  static SPB_LOCAL_FILTER = Routes.HARVEST + '/spb-local-filter'
  static SPB_LOCAL_LIST = Routes.HARVEST + '/spb-local-list'
  static SPB_LOCAL_FORM = Routes.HARVEST + '/spb-local-form'
  static SPB_LOCAL_DETAIL = Routes.HARVEST + '/spb-local-detail'

  static BPBKS_FILTER = Routes.HARVEST + '/bpbks-filter'
  static BPBKS_LIST = Routes.PLAN + '/bpbks-list'
  static BPBKS_FORM = Routes.PLAN + '/bpbks-form'
  static BPBKS_DETAIL = Routes.PLAN + '/bpbks-detail'
  static BPBKS_EMPLOYEE_DETAIL = Routes.PLAN + '/bpbks-employee-detail'
  static QR_SCANNER = Routes.PLAN + '/qr-scanner'
  static CAMERA_PHOTO = Routes.PLAN + '/camera-photo'

  static BKM_TAKE_CARE_FILTER = Routes.TAKE_CARE + '/bkm-take-care-filter'
  static BKM_TAKE_CARE_LIST = Routes.TAKE_CARE + '/bkm-take-care-list'
  static BKM_TAKE_CARE_FORM = Routes.TAKE_CARE + '/bkm-take-care-form'
  static BKM_TAKE_CARE_MATERIAL_FORM = Routes.TAKE_CARE + '/bkm-take-care-material-form'
  static BKM_TAKE_CARE_DETAIL = Routes.TAKE_CARE + '/bkm-take-care-detail'
  static BKM_TAKE_CARE_EMPLOYEE_DETAIL = Routes.TAKE_CARE + '/bkm-take-care-employee-detail'
  static REALIZATION_FERTILIZATION_FILTER = Routes.TAKE_CARE + '/realization-fertilization-filter'
  static REALIZATION_FERTILIZATION_LIST = Routes.TAKE_CARE + '/realization-fertilization-list'
  static REALIZATION_FERTILIZATION_FORM = Routes.TAKE_CARE + '/realization-fertilization-form'
  static REALIZATION_FERTILIZATION_DETAIL = Routes.TAKE_CARE + '/realization-fertilization-detail'

  static REPORT_AKP_REPORT = Routes.REPORT + '/akp-report'
  static REPORT_AKP_PLAN = Routes.REPORT + '/akp-plan-table'
  static REPORT_AKP_REALIZATION = Routes.REPORT + '/akp-realization-table'
  static REPORT_AKP_PLAN_D = Routes.REPORT + '/akp-plan-table-d'
  static REPORT_AKP_REALIZATION_D = Routes.REPORT + '/akp-realization-table-d'
  static REPORT_BPBKS = Routes.REPORT + '/bpbks-table'
  static REPORT_RKB_HARVEST = Routes.REPORT + '/rkb-harvest'
  static REPORT_RKB_MATERIAL = Routes.REPORT + '/rkb-see-material'
  static REPORT_YIELD_REPORT = Routes.REPORT + '/yield-report'
  static REPORT_RKB_TAKE_CARE = Routes.REPORT + '/rkb-takecare'
  static REPORT_BJB_PER_BLOK = Routes.REPORT + '/bjb-per-blok'
  static REPORT_BJB_PER_BLOK_D = Routes.REPORT + '/bjb-per-blok-d'
  static REPORT_EMPLOYEE_WAGE_CUT = Routes.REPORT + '/employee-wage-cut'
  static REPORT_EMPLOYEE_WAGE = Routes.REPORT + '/employee-wage'
  static REPORT_EMPLOYEE_WAGE_D = Routes.REPORT + '/employee-wage-d'
  static REPORT_RRP = Routes.REPORT + '/rrp'
  static REPORT_CROPBOOK = Routes.REPORT + '/cropbook'
  static REPORT_PMA = Routes.REPORT + '/pma'
  static REPORT_TONNAGE_GARDEN = Routes.REPORT + '/tonnage-garden'
  static REPORT_TONNAGE_PKS = Routes.REPORT + '/tonnage-pks'
  static REPORT_BPK = Routes.REPORT + '/report-bpk'
  static REPORT_BMP = Routes.REPORT + '/report-bmp'
  static REPORT_CHAPEL = Routes.REPORT + '/report-chapel'

  //deeplink report
  static SEE_BPK_MATERIAL = Routes.REPORT + '/see-bpk-material'

  //req
  static MY_REQUEST_LIST = Routes.REQUEST + '/my-request-list'
  static MY_REQUEST = Routes.REQUEST + '/my-request'
  static MY_REQUEST_FORM_TOOL = Routes.REQUEST + '/my-request-form-tool'
  static MY_REQUEST_FORM_MATERIAL = Routes.REQUEST + '/my-request-form-material'
  static MY_REQUEST_FORM_TRANSPORTATION = Routes.REQUEST + '/my-request-form-transportation'
  static MY_REQUEST_FORM_CASH = Routes.REQUEST + '/my-request-form-cash'
  static MY_REQUEST_FORM_FIRST = Routes.REQUEST + '/my-request-form-first'
  static WAREHOUSE_MANAGEMENT = Routes.REQUEST + '/warehouse-management'
  static WAREHOUSE_MANAGEMENT_LIST = Routes.REQUEST + '/warehouse-management-list'
  static WAREHOUSE_MANAGEMENT_DETAIL = Routes.REQUEST + '/warehouse-management-detail'
  static WAREHOUSE_MANAGEMENT_BPU = Routes.REQUEST + '/warehouse-management-bpu'
  static WAREHOUSE_MANAGEMENT_DETAIL_DESCRIPTION = Routes.REQUEST + '/warehouse-management-detail-description'
  static LIST_OF_REQUEST = Routes.REQUEST + '/list-of-request'
  static MY_REQUEST_FILTER = Routes.REQUEST + '/my-request-filter'
  static WAREHOUSE_MANAGEMENT_FILTER = Routes.REQUEST + '/warehouse-management-filter'
  static LIST_OF_REQUEST_FILTER = Routes.REQUEST + '/list-of-request-filter'

  static MY_REQUEST_DETAIL = Routes.REQUEST + '/my-request-detail'
  static LIST_OF_REQUEST_DETAIL = Routes.REQUEST + '/list-of-request-detail'

  //field report / berita acara
  static FIELD_REPORT = 'field-report'
  static FIELD_REPORT_FILTER = Routes.FIELD_REPORT + '/field-report-filter'
  static FIELD_REPORT_LIST = Routes.FIELD_REPORT + '/field-report-list'
  static FIELD_REPORT_FORM = Routes.FIELD_REPORT + '/field-report-form'
  static FIELD_REPORT_DETAIL = Routes.FIELD_REPORT + '/field-report-detail'
  static FIELD_REPORT_PREVIEW_IMAGE = Routes.FIELD_REPORT + '/field-report-preview-image'

  //common
  static COMMON = 'common'
  static COMMON_INFORMATION_LONG = Routes.COMMON + '/common-information'
}
