export const CREATE_LEAD_REQUEST = '$CRM_LEADS/CREATE_LEAD_REQUEST'
export const CREATE_LEAD_SUCCESS = '$CRM_LEADS/CREATE_LEAD_SUCCESS'
export const CREATE_LEAD_FAILURE = '$CRM_LEADS/CREATE_LEAD_FAILURE'

export const EDIT_LEAD_REQUEST = '$CRM_LEADS/EDIT_LEAD_REQUEST'
export const EDIT_LEAD_SUCCESS = '$CRM_LEADS/EDIT_LEAD_SUCCESS'
export const EDIT_LEAD_FAILURE = '$CRM_LEADS/EDIT_LEAD_FAILURE'

export const SYNC_LEADS_REQUEST = '$CRM_LEADS/SYNC_LEADS_REQUEST'
export const SYNC_LEADS_SUCCESS = '$CRM_LEADS/SYNC_LEADS_SUCCESS'
export const SYNC_LEADS_FAILURE = '$CRM_LEADS/SYNC_LEADS_FAILURE'

export const CREATE_OR_EDIT_LEAD_CLEAR = '$CRM_LEADS/CREATE_OR_EDIT_LEAD_CLEAR'

export const DELETE_LEAD_REQUEST = '$CRM_LEADS/DELETE_LEAD_REQUEST'
export const DELETE_LEAD_SUCCESS = '$CRM_LEADS/DELETE_LEAD_SUCCESS'
export const DELETE_LEAD_FAILURE = '$CRM_LEADS/DELETE_LEAD_FAILURE'
export const DELETE_LEAD_CLEAR = '$CRM_LEADS/DELETE_LEAD_CLEAR'

export const GET_LEAD_LIST_REQUEST = '$CRM_LEADS/GET_LEAD_LIST_REQUEST'
export const GET_LEAD_LIST_SUCCESS = '$CRM_LEADS/GET_LEAD_LIST_SUCCESS'
export const GET_LEAD_LIST_FAILURE = '$CRM_LEADS/GET_LEAD_LIST_FAILURE'

export const ADD_LEAD_TEMP = '$CRM_LEADS/ADD_LEAD_TEMP'
export const EDIT_LEAD_TEMP = '$CRM_LEADS/EDIT_LEAD_TEMP'
export const DELETE_LEAD_TEMP = '$CRM_LEADS/DELETE_LEAD_TEMP'
