export const CREATE_ATTENDANCE_MANUAL_REQUEST = '$ATTENDANCE/CREATE_ATTENDANCE_MANUAL_REQUEST'
export const CREATE_ATTENDANCE_MANUAL_SUCCESS = '$ATTENDANCE/CREATE_ATTENDANCE_MANUAL_SUCCESS'
export const CREATE_ATTENDANCE_MANUAL_FAILURE = '$ATTENDANCE/CREATE_ATTENDANCE_MANUAL_FAILURE'

export const CREATE_ATTENDANCE_UPLOAD_REQUEST = '$ATTENDANCE/CREATE_ATTENDANCE_UPLOAD_REQUEST'
export const CREATE_ATTENDANCE_UPLOAD_SUCCESS = '$ATTENDANCE/CREATE_ATTENDANCE_UPLOAD_SUCCESS'
export const CREATE_ATTENDANCE_UPLOAD_FAILURE = '$ATTENDANCE/CREATE_ATTENDANCE_UPLOAD_FAILURE'

export const CREATE_OR_EDIT_ATTENDANCE_CLEAR = '$ATTENDANCE/CREATE_OR_EDIT_ATTENDANCE_CLEAR'
export const CREATE_ATTENDANCE_TEMPORARY = '$ATTENDANCE/CREATE_ATTENDANCE_TEMPORARY'
export const SYNC_ATTENDANCES = '$ATTENDANCE/SYNC_ATTENDANCE'
export const DELETE_TEMPORARY_ATTENDANCE = '$ATTENDANCE/DELETE_TEMP_ATTENDANCE'

export const DELETE_ATTENDANCE_REQUEST = '$ATTENDANCE/DELETE_ATTENDANCE_REQUEST'
export const DELETE_ATTENDANCE_SUCCESS = '$ATTENDANCE/DELETE_ATTENDANCE_SUCCESS'
export const DELETE_ATTENDANCE_FAILURE = '$ATTENDANCE/DELETE_ATTENDANCE_FAILURE'
export const DELETE_ATTENDANCE_CLEAR = '$ATTENDANCE/DELETE_ATTENDANCE_CLEAR'

export const GET_ATTENDANCE_LIST_REQUEST = '$ATTENDANCE/GET_ATTENDANCE_LIST_REQUEST'
export const GET_ATTENDANCE_LIST_SUCCESS = '$ATTENDANCE/GET_ATTENDANCE_LIST_SUCCESS'
export const GET_ATTENDANCE_LIST_FAILURE = '$ATTENDANCE/GET_ATTENDANCE_LIST_FAILURE'

export const CLEAR_DRAFT_ATTENDANCE_REQUEST = '$ATTENDANCE/CLEAR_DRAFT_ATTENDANCE_REQUEST'
export const CLEAR_DRAFT_ATTENDANCE_SUCCESS = '$ATTENDANCE/CLEAR_DRAFT_ATTENDANCE_SUCCESS'
export const CLEAR_DRAFT_ATTENDANCE_FAILURE = '$ATTENDANCE/CLEAR_DRAFT_ATTENDANCE_FAILURE'
