export const GET_TAXATION_PAGINATED_REQUEST = '$EPLANT_TAXATION/GET_TAXATION_PAGINATED_REQUEST'
export const GET_TAXATION_PAGINATED_SUCCESS = '$EPLANT_TAXATION/GET_TAXATION_PAGINATED_SUCCESS'
export const GET_TAXATION_PAGINATED_FAILURE = '$EPLANT_TAXATION/GET_TAXATION_PAGINATED_FAILURE'

export const CREATE_TAXATION_REQUEST = '$EPLANT_TAXATION/CREATE_TAXATION_REQUEST'
export const CREATE_TAXATION_SUCCESS = '$EPLANT_TAXATION/CREATE_TAXATION_SUCCESS'
export const CREATE_TAXATION_FAILURE = '$EPLANT_TAXATION/CREATE_TAXATION_FAILURE'

export const EDIT_TAXATION_REQUEST = '$EPLANT_TAXATION/EDIT_TAXATION_REQUEST'
export const EDIT_TAXATION_SUCCESS = '$EPLANT_TAXATION/EDIT_TAXATION_SUCCESS'
export const EDIT_TAXATION_FAILURE = '$EPLANT_TAXATION/EDIT_TAXATION_FAILURE'

export const DELETE_TAXATION_REQUEST = '$EPLANT_TAXATION/DELETE_TAXATION_REQUEST'
export const DELETE_TAXATION_SUCCESS = '$EPLANT_TAXATION/DELETE_TAXATION_SUCCESS'
export const DELETE_TAXATION_FAILURE = '$EPLANT_TAXATION/DELETE_TAXATION_FAILURE'
export const DELETE_TAXATION_CLEAR = '$EPLANT_TAXATION/DELETE_TAXATION_CLEAR'

export const GET_HA_REALIZATION_TAXATION_REQUEST = '$EPLANT_TAXATION/GET_HA_REALIZATION_TAXATION_REQUEST'
export const GET_HA_REALIZATION_TAXATION_SUCCESS = '$EPLANT_TAXATION/GET_HA_REALIZATION_TAXATION_SUCCESS'
export const GET_HA_REALIZATION_TAXATION_FAILURE = '$EPLANT_TAXATION/GET_HA_REALIZATION_TAXATION_FAILURE'

export const GET_HA_REALIZATION_TAXATION_DETAIL_REQUEST = '$EPLANT_TAXATION/GET_HA_REALIZATION_TAXATION_DETAIL_REQUEST'
export const GET_HA_REALIZATION_TAXATION_DETAIL_SUCCESS = '$EPLANT_TAXATION/GET_HA_REALIZATION_TAXATION_DETAIL_SUCCESS'
export const GET_HA_REALIZATION_TAXATION_DETAIL_FAILURE = '$EPLANT_TAXATION/GET_HA_REALIZATION_TAXATION_DETAIL_FAILURE'

export const CREATE_OR_EDIT_TAXATION_CLEAR = '$EPLANT_TAXATION/CLEAR_FORM'
