export const CREATE_RKH_HARVEST_REQUEST = '$RKH/CREATE_RKH_HARVEST_REQUEST'
export const CREATE_RKH_HARVEST_SUCCESS = '$RKH/CREATE_RKH_HARVEST_SUCCESS'
export const CREATE_RKH_HARVEST_FAILURE = '$RKH/CREATE_RKH_HARVEST_FAILURE'

export const EDIT_RKH_HARVEST_REQUEST = '$RKH/EDIT_RKH_HARVEST_REQUEST'
export const EDIT_RKH_HARVEST_SUCCESS = '$RKH/EDIT_RKH_HARVEST_SUCCESS'
export const EDIT_RKH_HARVEST_FAILURE = '$RKH/EDIT_RKH_HARVEST_FAILURE'

export const DETAIL_RKH_HARVEST_REQUEST = '$RKH/DETAIL_RKH_HARVEST_REQUEST'
export const DETAIL_RKH_HARVEST_SUCCESS = '$RKH/DETAIL_RKH_HARVEST_SUCCESS'
export const DETAIL_RKH_HARVEST_FAILURE = '$RKH/DETAIL_RKH_HARVEST_FAILURE'

export const SYNC_RKH_HARVEST_REQUEST = '$RKH/SYNC_RKH_HARVEST_REQUEST'
export const SYNC_RKH_HARVEST_SUCCESS = '$RKH/SYNC_RKH_HARVEST_SUCCESS'
export const SYNC_RKH_HARVEST_FAILURE = '$RKH/SYNC_RKH_HARVEST_FAILURE'

export const CREATE_OR_EDIT_RKH_HARVEST_CLEAR = '$RKH/CREATE_OR_EDIT_RKH_HARVEST_CLEAR'

export const GET_RKH_HARVEST_LIST_REQUEST = '$RKH/GET_RKH_HARVEST_LIST_REQUEST'
export const GET_RKH_HARVEST_LIST_SUCCESS = '$RKH/GET_RKH_HARVEST_LIST_SUCCESS'
export const GET_RKH_HARVEST_LIST_FAILURE = '$RKH/GET_RKH_HARVEST_LIST_FAILURE'

export const GET_ALL_RKH_HARVEST_REQUEST = '$RKH/GET_ALL_RKH_HARVEST_REQUEST'
export const GET_ALL_RKH_HARVEST_SUCCESS = '$RKH/GET_ALL_RKH_HARVEST_SUCCESS'
export const GET_ALL_RKH_HARVEST_FAILURE = '$RKH/GET_ALL_RKH_HARVEST_FAILURE'

export const ADD_RKH_HARVEST_TEMP = '$RKH/ADD_RKH_HARVEST_TEMP'
export const EDIT_RKH_HARVEST_TEMP = '$RKH/EDIT_RKH_HARVEST_TEMP'
export const DELETE_RKH_HARVEST_TEMP = '$RKH/DELETE_RKH_HARVEST_TEMP'
