export const CREATE_MAINTENANCE_REQUEST = '$EPLANT_MAINTENANCE/CREATE_MAINTENANCE_REQUEST'
export const CREATE_MAINTENANCE_SUCCESS = '$EPLANT_MAINTENANCE/CREATE_MAINTENANCE_SUCCESS'
export const CREATE_MAINTENANCE_FAILURE = '$EPLANT_MAINTENANCE/CREATE_MAINTENANCE_FAILURE'
export const CREATE_OR_EDIT_MAINTENANCE_CLEAR = '$EPLANT_MAINTENANCE/CLEAR_FORM'

export const GET_MAINTENANCE_LIST_REQUEST = '$EPLANT_MAINTENANCE/GET_MAINTENANCE_LIST_REQUEST'
export const GET_MAINTENANCE_LIST_SUCCESS = '$EPLANT_MAINTENANCE/GET_MAINTENANCE_LIST_SUCCESS'
export const GET_MAINTENANCE_LIST_FAILURE = '$EPLANT_MAINTENANCE/GET_MAINTENANCE_LIST_FAILURE'

export const GET_MAINTENANCE_DETAIL_REQUEST = '$EPLANT_MAINTENANCE/GET_MAINTENANCE_DETAIL_REQUEST'
export const GET_MAINTENANCE_DETAIL_SUCCESS = '$EPLANT_MAINTENANCE/GET_MAINTENANCE_DETAIL_SUCCESS'
export const GET_MAINTENANCE_DETAIL_FAILURE = '$EPLANT_MAINTENANCE/GET_MAINTENANCE_DETAIL_FAILURE'

export const EDIT_MAINTENANCE_REQUEST = '$EPLANT_MAINTENANCE/EDIT_MAINTENANCE_REQUEST'
export const EDIT_MAINTENANCE_SUCCESS = '$EPLANT_MAINTENANCE/EDIT_MAINTENANCE_SUCCESS'
export const EDIT_MAINTENANCE_FAILURE = '$EPLANT_MAINTENANCE/EDIT_MAINTENANCE_FAILURE'

export const DELETE_MAINTENANCE_REQUEST = '$EPLANT_MAINTENANCE/DELETE_MAINTENANCE_REQUEST'
export const DELETE_MAINTENANCE_SUCCESS = '$EPLANT_MAINTENANCE/DELETE_MAINTENANCE_SUCCESS'
export const DELETE_MAINTENANCE_FAILURE = '$EPLANT_MAINTENANCE/DELETE_MAINTENANCE_FAILURE'
export const DELETE_MAINTENANCE_CLEAR = '$EPLANT_MAINTENANCE/CLEAR_DELETE_STATE'
