export const GET_SUBACTIVITY_ALL_REQUEST = '$SUB_ACTIVITY/GET_SUBACTIVITY_ALL_REQUEST'
export const GET_SUBACTIVITY_ALL_SUCCESS = '$SUB_ACTIVITY/GET_SUBACTIVITY_ALL_SUCCESS'
export const GET_SUBACTIVITY_ALL_FAILURE = '$SUB_ACTIVITY/GET_SUBACTIVITY_ALL_FAILURE'
