export const CREATE_RKH_REQUEST = '$RKH/CREATE_RKH_REQUEST'
export const CREATE_RKH_SUCCESS = '$RKH/CREATE_RKH_SUCCESS'
export const CREATE_RKH_FAILURE = '$RKH/CREATE_RKH_FAILURE'

export const EDIT_RKH_REQUEST = '$RKH/EDIT_RKH_REQUEST'
export const EDIT_RKH_SUCCESS = '$RKH/EDIT_RKH_SUCCESS'
export const EDIT_RKH_FAILURE = '$RKH/EDIT_RKH_FAILURE'

export const DETAIL_RKH_REQUEST = '$RKH/DETAIL_RKH_REQUEST'
export const DETAIL_RKH_SUCCESS = '$RKH/DETAIL_RKH_SUCCESS'
export const DETAIL_RKH_FAILURE = '$RKH/DETAIL_RKH_FAILURE'

export const SYNC_RKH_REQUEST = '$RKH/SYNC_RKH_REQUEST'
export const SYNC_RKH_SUCCESS = '$RKH/SYNC_RKH_SUCCESS'
export const SYNC_RKH_FAILURE = '$RKH/SYNC_RKH_FAILURE'

export const CREATE_OR_EDIT_RKH_CLEAR = '$RKH/CREATE_OR_EDIT_RKH_CLEAR'

export const DELETE_RKH_REQUEST = '$RKH/DELETE_RKH_REQUEST'
export const DELETE_RKH_SUCCESS = '$RKH/DELETE_RKH_SUCCESS'
export const DELETE_RKH_FAILURE = '$RKH/DELETE_RKH_FAILURE'
export const DELETE_RKH_CLEAR = '$RKH/DELETE_RKH_CLEAR'

export const GET_RKH_LIST_REQUEST = '$RKH/GET_RKH_LIST_REQUEST'
export const GET_RKH_LIST_SUCCESS = '$RKH/GET_RKH_LIST_SUCCESS'
export const GET_RKH_LIST_FAILURE = '$RKH/GET_RKH_LIST_FAILURE'

export const GET_ALL_RKH_REQUEST = '$RKH/GET_ALL_RKH_REQUEST'
export const GET_ALL_RKH_SUCCESS = '$RKH/GET_ALL_RKH_SUCCESS'
export const GET_ALL_RKH_FAILURE = '$RKH/GET_ALL_RKH_FAILURE'

export const ADD_RKH_TEMP = '$RKH/ADD_RKH_TEMP'
export const EDIT_RKH_TEMP = '$RKH/EDIT_RKH_TEMP'
export const DELETE_RKH_TEMP = '$RKH/DELETE_RKH_TEMP'

export const GET_RKH_SUMMARY_REQUEST = '$RKH/RKH_SUMMARY_REQUEST'
export const GET_RKH_SUMMARY_SUCCESS = '$RKH/RKH_SUMMARY_SUCCESS'
export const GET_RKH_SUMMARY_FAILURE = '$RKH/RKH_SUMMARY_FAILURE'

export const CLEAR_RKH_SUMMARY = '$RKH/RKH_SUMMARY_CLEAR'

export const CLEAR_DRAFT_RKH_REQUEST = '$RKH/CLEAR_DRAFT_RKH_REQUEST'
export const CLEAR_DRAFT_RKH_SUCCESS = '$RKH/CLEAR_DRAFT_RKH_SUCCESS'
export const CLEAR_DRAFT_RKH_FAILURE = '$RKH/CLEAR_DRAFT_RKH_FAILURE'
