export const CREATE_RAW_MATERIAL_REQUEST = '$RAW_MATERIAL/CREATE_RAW_MATERIAL_REQUEST'
export const CREATE_RAW_MATERIAL_SUCCESS = '$RAW_MATERIAL/CREATE_RAW_MATERIAL_SUCCESS'
export const CREATE_RAW_MATERIAL_FAILURE = '$RAW_MATERIAL/CREATE_RAW_MATERIAL_FAILURE'

export const UPDATE_RAW_MATERIAL_REQUEST = '$RAW_MATERIAL/UPDATE_RAW_MATERIAL_REQUEST'
export const UPDATE_RAW_MATERIAL_SUCCESS = '$RAW_MATERIAL/UPDATE_RAW_MATERIAL_SUCCESS'
export const UPDATE_RAW_MATERIAL_FAILURE = '$RAW_MATERIAL/UPDATE_RAW_MATERIAL_FAILURE'

export const GET_RAW_MATERIAL_LIST_REQUEST = '$RAW_MATERIAL/GET_RAW_MATERIAL_LIST_REQUEST'
export const GET_RAW_MATERIAL_LIST_SUCCESS = '$RAW_MATERIAL/GET_RAW_MATERIAL_LIST_SUCCESS'
export const GET_RAW_MATERIAL_LIST_FAILURE = '$RAW_MATERIAL/GET_RAW_MATERIAL_LIST_FAILURE'

export const GET_RAW_MATERIAL_ALL_REQUEST = '$RAW_MATERIAL/GET_RAW_MATERIAL_ALL_REQUEST'
export const GET_RAW_MATERIAL_ALL_SUCCESS = '$RAW_MATERIAL/GET_RAW_MATERIAL_ALL_SUCCESS'
export const GET_RAW_MATERIAL_ALL_FAILURE = '$RAW_MATERIAL/GET_RAW_MATERIAL_ALL_FAILURE'

export const GET_RAW_MATERIAL_DETAIL_REQUEST = '$RAW_MATERIAL/GET_RAW_MATERIAL_DETAIL_REQUEST'
export const GET_RAW_MATERIAL_DETAIL_SUCCESS = '$RAW_MATERIAL/GET_RAW_MATERIAL_DETAIL_SUCCESS'
export const GET_RAW_MATERIAL_DETAIL_FAILURE = '$RAW_MATERIAL/GET_RAW_MATERIAL_DETAIL_FAILURE'

export const CREATE_PURCHASEMENT_HISTORY_REQUEST = '$RAW_MATERIAL/CREATE_PURCHASEMENT_HISTORY_REQUEST'
export const CREATE_PURCHASEMENT_HISTORY_SUCCESS = '$RAW_MATERIAL/CREATE_PURCHASEMENT_HISTORY_SUCCESS'
export const CREATE_PURCHASEMENT_HISTORY_FAILURE = '$RAW_MATERIAL/CREATE_PURCHASEMENT_HISTORY_FAILURE'

export const GET_NORM_MATERIAL_REQUEST = '$RAW_MATERIAL/GET_NORM_MATERIAL_REQUEST'
export const GET_NORM_MATERIAL_SUCCESS = '$RAW_MATERIAL/GET_NORM_MATERIAL_SUCCESS'
export const GET_NORM_MATERIAL_FAILURE = '$RAW_MATERIAL/GET_NORM_MATERIAL_FAILURE'

export const EDIT_PURCHASEMENT_HISTORY_REQUEST = '$RAW_MATERIAL/EDIT_PURCHASEMENT_HISTORY_REQUEST'
export const EDIT_PURCHASEMENT_HISTORY_SUCCESS = '$RAW_MATERIAL/EDIT_PURCHASEMENT_HISTORY_SUCCESS'
export const EDIT_PURCHASEMENT_HISTORY_FAILURE = '$RAW_MATERIAL/EDIT_PURCHASEMENT_HISTORY_FAILURE'

export const UPDATE_RECEPTION_HISTORY_REQUEST = '$RAW_MATERIAL/UPDATE_RECEPTION_HISTORY_REQUEST'
export const UPDATE_RECEPTION_HISTORY_SUCCESS = '$RAW_MATERIAL/UPDATE_RECEPTION_HISTORY_SUCCESS'
export const UPDATE_RECEPTION_HISTORY_FAILURE = '$RAW_MATERIAL/UPDATE_RECEPTION_HISTORY_FAILURE'

export const GET_PURCHASEMENT_HISTORY_LIST_REQUEST = '$RAW_MATERIAL/GET_PURCHASEMENT_HISTORY_LIST_REQUEST'
export const GET_PURCHASEMENT_HISTORY_LIST_SUCCESS = '$RAW_MATERIAL/GET_PURCHASEMENT_HISTORY_LIST_SUCCESS'
export const GET_PURCHASEMENT_HISTORY_LIST_FAILURE = '$RAW_MATERIAL/GET_PURCHASEMENT_HISTORY_LIST_FAILURE'

export const GET_RECEPTION_HISTORY_LIST_REQUEST = '$RAW_MATERIAL/GET_RECEPTION_HISTORY_LIST_REQUEST'
export const GET_RECEPTION_HISTORY_LIST_SUCCESS = '$RAW_MATERIAL/GET_RECEPTION_HISTORY_LIST_SUCCESS'
export const GET_RECEPTION_HISTORY_LIST_FAILURE = '$RAW_MATERIAL/GET_RECEPTION_HISTORY_LIST_FAILURE'

export const GET_NORMA_SUBACTIVITY_REQUEST = '$RAW_MATERIAL/GET_NORMA_SUBACTIVITY_REQUEST'
export const GET_NORMA_SUBACTIVITY_SUCCESS = '$RAW_MATERIAL/GET_NORMA_SUBACTIVITY_SUCCESS'
export const GET_NORMA_SUBACTIVITY_FAILURE = '$RAW_MATERIAL/GET_NORMA_SUBACTIVITY_FAILURE'

export const DELETE_RAW_MATERIAL_REQUEST = '$RAW_MATERIAL/DELETE_RAW_MATERIAL_REQUEST'
export const DELETE_RAW_MATERIAL_SUCCESS = '$RAW_MATERIAL/DELETE_RAW_MATERIAL_SUCCESS'
export const DELETE_RAW_MATERIAL_FAILURE = '$RAW_MATERIAL/DELETE_RAW_MATERIAL_FAILURE'

export const CREATE_EDIT_RAW_MATERIAL_CLEAR_STATUS = '$RAW_MATERIAL/CREATE_EDIT_RAW_MATERIAL_CLEAR_STATUS'
export const CREATE_EDIT_PURCHASEMENT_HISTORY_CLEAR_STATUS =
  '$RAW_MATERIAL/CREATE_EDIT_PURCHASEMENT_HISTORY_CLEAR_STATUS'

export const EDIT_RECEPTION_HISTORY_CLEAR_STATUS = '$RAW_MATERIAL/EDIT_RECEPTION_HISTORY_CLEAR_STATUS'
export const DELETE_RAW_MATERIAL_CLEAR = '$RAW_MATERIAL/CLEAR_DELETE_STATE'
export const CLEAR_NORMA_SUBACTIVITY = '$RAW_MATERIAL/CLEAR_NORMA_SUBACTIVITY'
