export const CREATE_TPH_REQUEST = '$TPH/CREATE_TPH_REQUEST'
export const CREATE_TPH_SUCCESS = '$TPH/CREATE_TPH_SUCCESS'
export const CREATE_TPH_FAILURE = '$TPH/CREATE_TPH_FAILURE'

export const EDIT_TPH_REQUEST = '$TPH/EDIT_TPH_REQUEST'
export const EDIT_TPH_SUCCESS = '$TPH/EDIT_TPH_SUCCESS'
export const EDIT_TPH_FAILURE = '$TPH/EDIT_TPH_FAILURE'

export const CREATE_OR_EDIT_TPH_CLEAR = '$TPH/CREATE_OR_EDIT_TPH_CLEAR'

export const DELETE_TPH_REQUEST = '$TPH/DELETE_TPH_REQUEST'
export const DELETE_TPH_SUCCESS = '$TPH/DELETE_TPH_SUCCESS'
export const DELETE_TPH_FAILURE = '$TPH/DELETE_TPH_FAILURE'
export const DELETE_TPH_CLEAR = '$TPH/DELETE_TPH_CLEAR'

export const GET_TPH_LIST_REQUEST = '$TPH/GET_TPH_LIST_REQUEST'
export const GET_TPH_LIST_SUCCESS = '$TPH/GET_TPH_LIST_SUCCESS'
export const GET_TPH_LIST_FAILURE = '$TPH/GET_TPH_LIST_FAILURE'

export const GET_TPH_DETAIL_REQUEST = '$TPH/GET_TPH_DETAIL_REQUEST'
export const GET_TPH_DETAIL_SUCCESS = '$TPH/GET_TPH_DETAIL_SUCCESS'
export const GET_TPH_DETAIL_FAILURE = '$TPH/GET_TPH_DETAIL_FAILURE'

export const GET_TPH_ALL_REQUEST = '$TPH/GET_TPH_ALL_REQUEST'
export const GET_TPH_ALL_SUCCESS = '$TPH/GET_TPH_ALL_SUCCESS'
export const GET_TPH_ALL_FAILURE = '$TPH/GET_TPH_ALL_FAILURE'
