export const GET_MONITORING_TPH_LIST_REQUEST = '$MONITORING_TPH/GET_LIST_REQUEST'
export const GET_MONITORING_TPH_LIST_SUCCESS = '$MONITORING_TPH/GET_LIST_SUCCESS'
export const GET_MONITORING_TPH_LIST_FAILURE = '$MONITORING_TPH/GET_LIST_FAILURE'

export const GET_MONITORING_TPH_SUMMARY_REQUEST = '$MONITORING_TPH/GET_SUMMARY_REQUEST'
export const GET_MONITORING_TPH_SUMMARY_SUCCESS = '$MONITORING_TPH/GET_SUMMARY_SUCCESS'
export const GET_MONITORING_TPH_SUMMARY_FAILURE = '$MONITORING_TPH/GET_SUMMARY_FAILURE'

export const CLEAR_MONITORING_TPH = '$MONITORING_TPH/CLEAR'
export const SET_MONITORING_TPH_LAST_UPDATED = '$MONITORING_TPH/SET_LAST_UPDATED'
