export const CREATE_BKM_REQUEST = '$AKP/CREATE_BKM_REQUEST'
export const CREATE_BKM_SUCCESS = '$AKP/CREATE_BKM_SUCCESS'
export const CREATE_BKM_FAILURE = '$AKP/CREATE_BKM_FAILURE'

export const EDIT_BKM_REQUEST = '$AKP/EDIT_BKM_REQUEST'
export const EDIT_BKM_SUCCESS = '$AKP/EDIT_BKM_SUCCESS'
export const EDIT_BKM_FAILURE = '$AKP/EDIT_BKM_FAILURE'

export const DETAIL_BKM_REQUEST = '$AKP/DETAIL_BKM_REQUEST'
export const DETAIL_BKM_SUCCESS = '$AKP/DETAIL_BKM_SUCCESS'
export const DETAIL_BKM_FAILURE = '$AKP/DETAIL_BKM_FAILURE'

export const MOBILE_BKM_REQUEST = '$AKP/MOBILE_BKM_REQUEST'
export const MOBILE_BKM_SUCCESS = '$AKP/MOBILE_BKM_SUCCESS'
export const MOBILE_BKM_FAILURE = '$AKP/MOBILE_BKM_FAILURE'

export const SYNC_BKM_REQUEST = '$AKP/SYNC_BKM_REQUEST'
export const SYNC_BKM_SUCCESS = '$AKP/SYNC_BKM_SUCCESS'
export const SYNC_BKM_FAILURE = '$AKP/SYNC_BKM_FAILURE'

export const CREATE_OR_EDIT_BKM_CLEAR = '$AKP/CREATE_OR_EDIT_BKM_CLEAR'

export const DELETE_BKM_REQUEST = '$AKP/DELETE_BKM_REQUEST'
export const DELETE_BKM_SUCCESS = '$AKP/DELETE_BKM_SUCCESS'
export const DELETE_BKM_FAILURE = '$AKP/DELETE_BKM_FAILURE'
export const DELETE_BKM_CLEAR = '$AKP/DELETE_BKM_CLEAR'

export const GET_BKM_LIST_REQUEST = '$AKP/GET_BKM_LIST_REQUEST'
export const GET_BKM_LIST_SUCCESS = '$AKP/GET_BKM_LIST_SUCCESS'
export const GET_BKM_LIST_FAILURE = '$AKP/GET_BKM_LIST_FAILURE'

export const GET_ALL_BKM_REQUEST = '$AKP/GET_ALL_BKM_REQUEST'
export const GET_ALL_BKM_SUCCESS = '$AKP/GET_ALL_BKM_SUCCESS'
export const GET_ALL_BKM_FAILURE = '$AKP/GET_ALL_BKM_FAILURE'

export const ADD_BKM_TEMP = '$AKP/ADD_BKM_TEMP'
export const EDIT_BKM_TEMP = '$AKP/EDIT_BKM_TEMP'
export const DELETE_BKM_TEMP = '$AKP/DELETE_BKM_TEMP'
export const DELETE_BKM_EMPLOYEE_TEMP = '$AKP/DELETE_BKM_EMPLOYEE_TEMP'

export const CLEAR_DRAFT_BKM_REQUEST = '$AKP/CLEAR_DRAFT_BKM_REQUEST'
export const CLEAR_DRAFT_BKM_SUCCESS = '$AKP/CLEAR_DRAFT_BKM_SUCCESS'
export const CLEAR_DRAFT_BKM_FAILURE = '$AKP/CLEAR_DRAFT_BKM_FAILURE'
