export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE'

export const GET_UNREAD_COUNT_REQUEST = 'GET_UNREAD_COUNT_REQUEST'
export const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS'
export const GET_UNREAD_COUNT_FAILURE = 'GET_UNREAD_COUNT_FAILURE'

export const MARK_AS_READ_REQUEST = 'MARK_AS_READ_REQUEST'
export const MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS'
export const MARK_AS_READ_FAILURE = 'MARK_AS_READ_FAILURE'

export const MARK_ALL_READ_REQUEST = 'MARK_ALL_READ_REQUEST'
export const MARK_ALL_READ_SUCCESS = 'MARK_ALL_READ_SUCCESS'
export const MARK_ALL_READ_FAILURE = 'MARK_ALL_READ_FAILURE'

export const REGISTER_DEVICE_REQUEST = 'REGISTER_DEVICE_REQUEST'
export const REGISTER_DEVICE_SUCCESS = 'REGISTER_DEVICE_SUCCESS'
export const REGISTER_DEVICE_FAILURE = 'REGISTER_DEVICE_FAILURE'

export const CLEAR_NOTIFICATION_STATUS = 'CLEAR_NOTIFICATION_STATUS'