export const GET_PROVINCES_REQUEST = '$MASTER/GET_PROVINCES_REQUEST'
export const GET_PROVINCES_SUCCESS = '$MASTER/GET_PROVINCES_SUCCESS'
export const GET_PROVINCES_FAILURE = '$MASTER/GET_PROVINCES_FAILURE'

export const GET_UOM_REQUEST = '$MASTER/GET_UOM_REQUEST'
export const GET_UOM_SUCCESS = '$MASTER/GET_UOM_SUCCESS'
export const GET_UOM_FAILURE = '$MASTER/GET_UOM_FAILURE'

export const GET_RANGE_YEAR_REQUEST = '$MASTER/GET_RANGE_YEAR_REQUEST'
export const GET_RANGE_YEAR_FAILURE = '$MASTER/GET_RANGE_YEAR_FAILURE'
export const GET_RANGE_YEAR_SUCCESS = '$MASTER/GET_RANGE_YEAR_SUCCESS'

export const GET_RANGE_BREAK_TIME_REQUEST = '$MASTER/GET_RANGE_BREAK_TIME_REQUEST'
export const GET_RANGE_BREAK_TIME_FAILURE = '$MASTER/GET_RANGE_BREAK_TIME_FAILURE'
export const GET_RANGE_BREAK_TIME_SUCCESS = '$MASTER/GET_RANGE_BREAK_TIME_SUCCESS'

export const GET_TYPE_EMPLOYEE_REQUEST = '$MASTER/GET_TYPE_EMPLOYEE_REQUEST'
export const GET_TYPE_EMPLOYEE_FAILURE = '$MASTER/GET_TYPE_EMPLOYEE_FAILURE'
export const GET_TYPE_EMPLOYEE_SUCCESS = '$MASTER/GET_TYPE_EMPLOYEE_SUCCESS'

export const GET_SUPERVISIONS_REQUEST = '$MASTER/GET_SUPERVISIONS_REQUEST'
export const GET_SUPERVISIONS_SUCCESS = '$MASTER/GET_SUPERVISIONS_SUCCESS'
export const GET_SUPERVISIONS_FAILURE = '$MASTER/GET_SUPERVISIONS_FAILURE'

export const GET_WORK_STATUS_REQUEST = '$MASTER/GET_WORK_STATUS_REQUEST'
export const GET_WORK_STATUS_SUCCESS = '$MASTER/GET_WORK_STATUS_SUCCESS'
export const GET_WORK_STATUS_FAILURE = '$MASTER/GET_WORK_STATUS_FAILURE'

export const GET_MINIMUM_AKP_REQUEST = '$MASTER/GET_MINIMUM_AKP_REQUEST'
export const GET_MINIMUM_AKP_SUCCESS = '$MASTER/GET_MINIMUM_AKP_SUCCESS'
export const GET_MINIMUM_AKP_FAILURE = '$MASTER/GET_MINIMUM_AKP_FAILURE'
